(TeX-add-style-hook
 "02-01-pp68-77"
 (lambda ()
   (LaTeX-add-labels
    "garnitures"
    "serie-des-farces-diverses"
    "les-panades-pour-farces"
    "panades"
    "panade-a"
    "panade-b"
    "panade-c"
    "panade-d"
    "panade-e"
    "farces"
    "farce-a"
    "nota-farce-a"
    "farce-b"
    "nota-farce-b"
    "farce-c"
    "nota-farce-c"
    "godiveau"
    "godiveau-mouille-a-la-glace"
    "nota-godiveau-a"
    "godiveau-a-la-creme"
    "godiveau-lyonnais"
    "farce-de-veau-pour-bordures"
    "farce-gratin-a"
    "nota-farce-gratin-a"
    "farce-gratin-b"
    "farce-gratin-c"
    "farce-pour-les-pieces-froides"
    "assaisonnement-et-liaison"
    "sel-epice"
    "farce-froide-a"
    "chair-a-saucisse"
    "farce-froide-b"
    "farce-froide-c"
    "observation-sur-les-farces"
    "farces-speciales-pour-garnir-les-poissons-braises"
    "farces-poissons-braises-a"
    "farces-poissons-braises-b"
    "ux30afux30cdux30eb54")
   (LaTeX-add-index-entries
    "garnitures@garnitures"
    "かるにちゆーる@ガルニチュール"
    "garnitures@garnitures!farces@farces"
    "farce@farce"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス"
    "ふあるす@ファルス"
    "farce@farce!panade@les panades pour farces"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!はなーと@パナード"
    "ふあるす@ファルス!はなーと@---用パナード"
    "panade"
    "garniture!panade"
    "garniture!farce!panade"
    "はなーと@パナード"
    "garnitures@garnitures!farces@farces!panade a@panade A"
    "farce@farce!panade@les panades pour farces!panade a@panade A"
    "panade!a pain@A. --- au pain"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!はなーとa@パナードA. パンの---"
    "ふあるす@ファルス!はなーと@---用パナード!a@A. パンのパナード"
    "はなーと@パナード!a@A. パンの---"
    "garnitures@garnitures!farces@farces!panade b@panade B"
    "farce@farce!panade@les panades pour farces!panade b@panade B"
    "panade!b farine@B. --- à la farine"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!はなーとb@パナードB. 小麦粉の---"
    "ふあるす@ファルス!はなーと@---用パナード!b@パナードB. 小麦粉の---"
    "はなーと@パナード!b@B. 小麦粉の---"
    "garnitures@garnitures!farces@farces!panade c@panade C"
    "farce@farce!panade@les panades pour farces!panade c@panade C"
    "panade!c frangipane@C. --- à la Frangipane"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!はなーとc@パナードC"
    "ふあるす@ファルス!はなーと@---用パナード!はなーとC@パナードC"
    "はなーと@パナード!c@C. ---・フランジパーヌ"
    "garnitures@garnitures!farces@farces!panade d@panade D"
    "farce@farce!panade@les panades pour farces!panade d@panade D"
    "panade!d riz@D. --- au Riz"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!はなーとd@パナードD. 米の---"
    "ふあるす@ファルス!はなーと@---用パナード!はなーとd@D. 米のパナード"
    "はなーと@パナード!d@D. 米の---"
    "garnitures@garnitures!farces@farces!panade e@panade E"
    "farce@farce!panade@les panades pour farces!panade e@panade E"
    "panade!e riz@E. --- à la pomme de terre"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!はなーとe@パナードE"
    "ふあるす@ファルス!はなーと@---用パナード!はなーとe@パナードE"
    "はなーと@パナード!e@E. じゃがいもの---"
    "farce"
    "garniture!farce"
    "farce!a@A. --- à la Panade et au beurre"
    "garniture!farce!a@A. Farce à la Panade et au beurre"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!a@A. パナードとバターを用いるファルス"
    "ふあるす@ファルス!a@A. パナードとバターを用いる---"
    "farce!b@B. --- à la Panade et à la crème"
    "garniture!farce!b@B. Farce à la Panade et à la crème"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!b@B. パナードと生クリームを用いるファルス"
    "ふあるす@ファルス!b@B. パナードと生クリームを用いる---"
    "farce!c@B. --- fine à la crème, ou Mousseline"
    "garniture!farce!c@C. Farce fine à la crème, ou Mousseline"
    "mousseline!farce mousseline"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!c@C. 生クリームを用いる滑らかなファルス/ファルス・ムスリーヌ"
    "ふあるす@ファルス!c@C. 生クリームを用いる滑らかな---/---・ムスリーヌ"
    "むすりーぬ@ムスリーヌ!ふあるす@ファルス・---"
    "farce!veau graisse de boeuf@--- de veau à la graisse de boeuf"
    "garniture!farce!veau graisse de boeuf@Farce de veau à la graisse de boeuf"
    "farce!veau glodiveau@Godiveau"
    "garniture!farce!godiveau@Godiveau"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!こうしにくとけんねあふらのふあるす@仔牛肉とケンネ脂のファルス/ゴディヴォ"
    "ふあるす@ファルス!こうしにくとけんねあふらのふあるす@牛仔牛肉とケンネ脂の---/ゴディヴォ"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!こていうお@ゴディヴォ"
    "ふあるす@ファルス!こていうお@ゴディヴォ"
    "godiveau"
    "こていうお@ゴディヴォ"
    "farce@farce!godiveau a@Godiveau A. Godeiveau mouillé à la glace"
    "ふあるす@ファルス!こていうお@ゴディヴォ!a@A. 氷を入れて作るゴディヴォ"
    "godiveau@godiveau!a@A. --- mouillé à la glace"
    "こていうお@ゴディヴォ!a@A. 氷を入れて作る---"
    "farce@farce!godiveau b@Godiveau B. Godeiveau  à la crème"
    "ふあるす@ファルス!こていうお@ゴディヴォ!b@B. 生クリーム入りゴディヴォ"
    "godiveau@godiveau!b@B. --- à la crème"
    "こていうお@ゴディヴォ!b@B. 生クリーム入り---"
    "farce@farce!godiveau c@Godiveau C. Godeiveau Lyonnais ou Farce de Brochet à la graisse"
    "ふあるす@ファルス!こていうお@ゴディヴォ!c@C. リヨン風ゴディヴォ/ケンネ脂入りブロシェのファルス"
    "godiveau@godiveau!c@C. --- Lyonnais ou Farce de Brochet à la graisse"
    "こていうお@ゴディヴォ!c@C. リヨン風---/ケンネ脂入りブロシェのファルス"
    "farce!veau@--- de veau pour Bordures de dressage, fonds, quenelles fourrées, etc."
    "garniture!farce!veau@Farce de veau pour Bordures de dressage, fonds, quenelles fourrées etc."
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!こうし@盛り付けの縁飾りおよび底に敷いたり、詰め物をしたクネルに用いる仔牛の---"
    "ふあるす@ファルス!こうし@盛り付けの縁飾りおよび底に敷いたり、詰め物をしたクネルに用いる仔牛の---"
    "garniture@garniture!farce@farce!gratin@Farce Gratin"
    "farce@farce!gratin@--- gratin"
    "gratin@gratin!farce@farce ---"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!くらたん@ファルス・グラタン"
    "ふあるす@ファルス!くらたん@ファルス・グラタン"
    "くらたん@グラタン!ふあるす@ファルス・---"
    "farce@farce!gratin a@--- Gratin A"
    "garniture@garniture!farce@farce!gratin a@Farce Gratin A"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!くらたんa@---・グラタン A"
    "ふあるす@ファルス!くらたんa@---・グラタン A"
    "farce@farce!gratin b@--- Gratin B"
    "garniture@garniture!farce!farce gratin b@Farce Gratin B"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!くらたんb@---・グラタン B"
    "ふあるす@ファルス!くらたんb@---・グラタン B"
    "farce@farce!gratin c@--- Gratin C"
    "garniture@garniture!farce!farce gratin c@Farce Gratin C"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!くらたんc@---・グラタン C"
    "ふあるす@ファルス!くらたんc@---・グラタン C"
    "farce@farce!piece froides@--- pour les pièces froides"
    "ふあるす@ファルス!れいせいりようりよう@冷製料理用の---"
    "sel epice@sel épicé"
    "すぱいすそると@スパイスソルト"
    "こうしんりよういりしお@香辛料入りの塩 ⇒ スパイスソルト"
    "farce@farce!froide a@--- pour les pièces froides A (Porc)"
    "garniture@garniture!farce!farce froides a@Farce pour les pièces froides A (Porc)"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!れいせいa@冷製料理用--- A"
    "ふあるす@ファルス!れいせいa@冷製料理用--- A"
    "farce@farce!froide b@--- pour les pièces froides B (Veau et Porc)"
    "garniture@garniture!farce!farce froides b@Farce pour les pièces froides B (Veau et Porc)"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!れいせいb@冷製料理用--- B"
    "ふあるす@ファルス!れいせいb@冷製料理用--- B"
    "farce@farce!froide c@--- pour les pièces froides C (Volaille et Gibier)"
    "garniture@garniture!farce!farce froides c@Farce pour les pièces froides C (Volaille et Gibier)"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!れいせいc@冷製料理用--- C"
    "ふあるす@ファルス!れいせいc@冷製料理用--- C"
    "farce@farce!poissons braises a@---s spéciales pour les poissons braisés A"
    "garniture@garniture!farce!farce poissons braises a@Farce spéciale pour les poissons braisés A"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!さかなのふれせa@魚のブレゼのガルニチュール用--- A"
    "ふあるす@ファルス!さかなのふれせa@魚のブレゼのガルニチュール用--- A"
    "farce@farce!poissons braises b@---s spéciales pour les poissons braisés B"
    "garniture@garniture!farce!farce poissons braises b@Farce spéciale pour les poissons braisés B"
    "かるにちゆーる@ガルニチュール!ふあるす@ファルス!さかなのふれせb@魚のブレゼのガルニチュール用--- B"
    "ふあるす@ファルス!さかなのふれせb@魚のブレゼのガルニチュール用--- B"))
 :latex)

