(TeX-add-style-hook
 "02-03-pp83-88"
 (lambda ()
   (LaTeX-add-labels
    "serie-des-appareiles-et-preparations-diverses-pour-garnitures-froides"
    "mousses-mousselines-et-souffles-froids"
    "composition-de-l-appareil-pour-mousses-et-mousseline-froides"
    "nota-composition-de-l-appareil-pour-mousses-et-mousseline-froides"
    "moulage-des-mousses-froides"
    "moulage-des-mousselines-froides"
    "procede-un-moulage-des-mousselines-froides"
    "procede-deux-moulage-des-mousselines-froides"
    "souffles-froids"
    "nota-souffles-froids"
    "aspics"
    "nota-aspics"
    "chauds-froids"
    "pains-froids"
    "garnitures-de-mets-froids"
    "serie-des-garnitures"
    "consideration-sur-la-modification-de-forme-que-peuvent-subir-les-garniture"
    "remarque-importante-sur-les-sauces-applicables-aux-entrees-de-boucherie-garnie-de-legumes")
   (LaTeX-add-index-entries
    "garniture@garniture!appareils garnitures froides@appareils et préparations diverses pour garnitures froides"
    "appareil@appareil!garnitures froides@--- et préparations diverses pour garnitures froides"
    "かるにちゆーる@ガルニチュール!あはれいゆれいせい@冷製ガルニチュールのためのアパレイユなど"
    "あはれいゆ@アパレイユ!れいせいかるにちゆーる@冷製ガルニチュールのための---など"
    "mousse@mousse!froide@--- froide"
    "mousseline@mousseline!froide@--- froide"
    "souffle@soufflé!froid@--- froid"
    "むーす@ムース!れいせい@冷製の---"
    "むすりーぬ@ムスリーヌ!れいせい@冷製の---"
    "すふれ@スフレ!れいせい@冷製の---"
    "garniture@garniture!appareils garnitures froides@appareils et préparations diverses pour garnitures froides!appareil mousses mousselines froides@composition de l'appareil pour mousses et mousselines froides"
    "appareil@appareil!garnitures froides@--- et préparations diverses pour garnitures froides!appareil mousses mousselines froides@composition de l'appareil pour mousses et mousselines froides"
    "mousse@mousse!froide@froide!composition appareil@Composition de l'appareil pour mousses et mousseline froides"
    "mousseline@mousseline!froide@froide!composition appareil@Composition de l'appareil pour mousses et mousseline froides"
    "かるにちゆーる@ガルニチュール!あはれいゆれいせい@冷製ガルニチュールのためのアパレイユなど!れいせいのむーすとむすりーぬのあぱれいゆ@冷製のムースとムスリーヌのアパレイユ"
    "あはれいゆ@アパレイユ!れいせいかるにちゆーる@冷製ガルニチュールのための---など!れいせいのむーすとむすりーぬのあぱれいゆ@冷製のムースとムスリーヌのアパレイユ"
    "むーす@ムース!れいせい@冷製!むーすとむすりーぬのあぱれいゆ@ムースとムスリーヌのアパレイユ"
    "むすりーぬ@ムスリーヌ!れいせい@冷製!むーすとむすりーぬのあぱれいゆ@ムースとムスリーヌのアパレイユ"
    "garniture@garniture!appareils garnitures froides@appareils et préparations diverses pour garnitures froides!moulage mousses froides@moulage des mousses froides"
    "appareil@appareil!garnitures froides@--- et préparations diverses pour garnitures froides!moulage mousses froides@moulage des mousses froides"
    "mousse@mousse!froide@froide!moulage@moulage des mousses froides"
    "かるにちゆーる@ガルニチュール!あはれいゆれいせい@冷製ガルニチュールのためのアパレイユなど!れいせいむーすのかたつめ@冷製ムースの型詰め"
    "あはれいゆ@アパレイユ!れいせいかるにちゆーる@冷製ガルニチュールのための---など!れいせいむーすのかたつめ@冷製ムースの型詰め"
    "むーす@ムース!れいせい@冷製!むーすのかたつめ@ムースの型詰め"
    "garniture@garniture!appareils garnitures froides@appareils et préparations diverses pour garnitures froides!moulage mousselines froides@moulage des mousselines froides"
    "appareil@appareil!garnitures froides@--- et préparations diverses pour garnitures froides!moulage mousselines froides@moulage des mousselines froides"
    "mousseline@mousseline!froide@froide!moulage@moulage des mousselines froides"
    "かるにちゆーる@ガルニチュール!あはれいゆれいせい@冷製ガルニチュールのためのアパレイユなど!れいせいむすりーぬのかたつめ@冷製ムスリーヌの型詰め"
    "あはれいゆ@アパレイユ!れいせいかるにちゆーる@冷製ガルニチュールのための---など!れいせいむすりーぬのかたつめ@冷製ムスリーヌの型詰め"
    "むすりーぬ@ムスリーヌ!れいせい@冷製!むすりーぬのかたつめ@ムスリーヌの型詰め"
    "garniture@garniture!appareils garnitures froides@appareils et préparations diverses pour garnitures froides!souffles froids@soufflés froids"
    "appareil@appareil!garnitures froides@--- et préparations diverses pour garnitures froides!souffles froids@soufflés froids"
    "souffle@soufflé!froid@---s froids"
    "かるにちゆーる@ガルニチュール!あはれいゆれいせい@冷製ガルニチュールのためのアパレイユなど!れいせいすふれ@冷製スフレ"
    "あはれいゆ@アパレイユ!れいせいかるにちゆーる@冷製ガルニチュールのための---など!れいせいすふれ@冷製スフレ"
    "すふれ@スフレ!れいせい@冷製---"
    "garniture@garniture!appareils garnitures froides@appareils et préparations diverses pour garnitures froides!aspics@aspics"
    "appareil@appareil!garnitures froides@--- et préparations diverses pour garnitures froides!aspics@aspics"
    "aspics@aspics (généralité)"
    "かるにちゆーる@ガルニチュール!あはれいゆれいせい@冷製ガルニチュールのためのアパレイユなど!あすぴつく@アスピック（概説）"
    "あはれいゆ@アパレイユ!れいせいかるにちゆーる@冷製ガルニチュールのための---など!あすぴつく@アスピック（概説）"
    "あすぴつく@アスピック（概説）"
    "garniture@garniture!appareils garnitures froides@appareils et préparations diverses pour garnitures froides!chauds-froids@chauds-froids"
    "appareil@appareil!garnitures froides@--- et préparations diverses pour garnitures froides!chauds-froids@chauds-froids"
    "chauds-froids@chauds-froids (généralité)"
    "かるにちゆーる@ガルニチュール!あはれいゆれいせい@冷製ガルニチュールのためのアパレイユなど!しよふろわ@ショフロワ（概説）"
    "あはれいゆ@アパレイユ!れいせいかるにちゆーる@冷製ガルニチュールのための---など!しよふろわ@ショフロワ（概説）"
    "しよふろわ@ショフロワ（概説）"
    "garniture@garniture!appareils garnitures froides@appareils et préparations diverses pour garnitures froides!pain froids@pain froids"
    "appareil@appareil!garnitures froides@--- et préparations diverses pour garnitures froides!pain froids@pain froids"
    "pains froids@pains froids (généralité)"
    "かるにちゆーる@ガルニチュール!あはれいゆれいせい@冷製ガルニチュールのためのアパレイユなど!はんふろわ@パンフロワ（概説）"
    "あはれいゆ@アパレイユ!れいせいかるにちゆーる@冷製ガルニチュールのための---など!はんふろわ@パンフロワ（概説）"
    "はんふろわ@パンフロワ（概説）"
    "garniture@garniture!appareils garnitures froides@appareils et préparations diverses pour garnitures froides!garnitures mets froids@garnitures de mets froids"
    "appareil@appareil!garnitures froides@--- et préparations diverses pour garnitures froides!garnitures mets froids@garnitures de mets froids"
    "garnitures mets froids@garnitures de mets froids (généralité)"
    "かるにちゆーる@ガルニチュール!あはれいゆれいせい@冷製ガルニチュールのためのアパレイユなど!れいせいりようりのかるにちゆーる@冷製料理のガルニチュール（概説）"
    "あはれいゆ@アパレイユ!れいせいかるにちゆーる@冷製ガルニチュールのための---など!れいせいりようりのかるにちゆーる@冷製料理のガルニチュール（概説）"
    "れいせいりようりのかるにちゆーる@冷製料理のガルニチュール（概説）"
    "garniture@garniture!consideration modification forme garnitures@Considération sur les modificqtions de forme que peuvent subir les Garnitures"
    "consideration@garnitures de mets froids (généralité)"
    "かるにちゆーる@ガルニチュール!みためをかえることについて@---の見た目を変えることについて"
    "garniture@garniture!remarque sauce entrees boucherie legumes@Remarque importante sur les sauces applicables aux Entrées de Boucherie garnies de Légumes"
    "かるにちゆーる@ガルニチュール!うしひつしにくりようりにやさいをそえるはあいにふさわしいそーす@牛、羊肉料理に野菜を添える場合にふさわしいソースについて"))
 :latex)

