(TeX-add-style-hook
 "01-02-pp13-17"
 (lambda ()
   (LaTeX-add-labels
    "grandes-sauces-de-base"
    "sauce-espagnole"
    "nota-sauce-espagnole"
    "sauce-espagnole-maigre"
    "observation-sauce-espagnole-maigre"
    "sauce-demi-glace"
    "nota-sauce-demi-glace"
    "jus-de-veau-lie"
    "nota-jus-de-veau-lie"
    "veloute"
    "veloute-de-volaille"
    "veloute-de-poisson"
    "sauce-allemande"
    "nota-sauce-allemande"
    "sauce-supreme"
    "sauce-bechamel"
    "sauce-tomate"
    "nota-sauce-tomate")
   (LaTeX-add-index-entries
    "そーす@ソース!きほん@基本---"
    "sauce@sauce!00grandes@*Grandes ---s de Base"
    "そーす@ソース!えすはによる@---・エスパニョル"
    "そーす@ソース!きほん@基本---!えすはによる@---・エスパニョル"
    "きほんそーす@基本ソース!えすはによる@---・エスパニョル"
    "えすはによる@エスパニョル!そーす@ソース・---"
    "すへいんふう@スペイン風（エスパニョル）!そーすえすはによる@ソース・エスパニョル"
    "sauce@sauce!00grandes@*Grandes ---s de Base!espagnole@--- Espagnole"
    "sauce@sauce!espagnole@--- Espagnole"
    "espagnol@espagnol!sauce@Sauce ---e"
    "みるほわ@ミルポワ"
    "mirepoix"
    "そーす@ソース!えすはによるるさかな@---・エスパニョル (魚料理用)"
    "そーす@ソース!きほん@基本---!えすはによるさかな@魚料理用---・エスパニョル"
    "きほんそーす@基本ソース!えすはによるさかな@魚料理用---・エスパニョル"
    "えすはによる@エスパニョル!そーすさかなよう@ソース・--- (魚料理用)"
    "すへいんふう@スペイン風（エスパニョル）!そーすえすはによるさかな@ソース・エスパニョル（魚料理用）"
    "sauce@sauce!00grandes@*Grandes ---s de Base!espagnole maigre@--- Espagnole maigre"
    "sauce@sauce!espagnole maigre@--- Espagnole maigre"
    "espagnol@espagnol!sauce maigre@Sauce Espagnole maigre"
    "そーす@ソース!とうみくらす@---・ドゥミグラス"
    "そーす@ソース!きほん@基本---!とうみくらす@---・ドゥミグラス"
    "きほんそーす@基本ソース!とうみくらす@---・ドゥミグラス"
    "sauce@sauce!00grandes@*Grandes ---s de Base!demi-glace@--- Demi-glace"
    "sauce@sauce!demi-glace@--- Demi-glace"
    "そーす@ソース!きほん@基本---!とろみをつけたこうしのしゆ@とろみを付けた仔牛のジュ"
    "きほんそーす@基本ソース!とろみをつけたこうしのしゆ@とろみを付けた仔牛のジュ"
    "しゆ@ジュ!こうしのしゆ@仔牛の---(とろみを付けた)"
    "そーす@ソース!とろみをつけたこうしのしゆ@とろみを付けた仔牛のジュ"
    "こうし@仔牛!とろみをつけたこうしのしゆ@とろみを付けた---のジュ"
    "sauce@sauce!00grandes@*Grandes ---s de Base!jus veau lie@--- de veau lié"
    "jus@jus!jus veau lie@--- de veau lié"
    "veau@veau!jus lie@jus de --- lié"
    "そーす@ソース!きほん@基本---!うるて@ヴルテ（標準的な）"
    "きほんそーす@基本ソース!うるて@ヴルテ（標準的な）"
    "うるて@ヴルテ!ひようひゆんてきなそーすうるて@標準的なソース・---"
    "そーす@ソース!うるてひようひゆん@ヴルテ（標準的な）"
    "ふるーて@ブルーテ ⇒ ヴルテ"
    "veloute@velouté"
    "veloute@velouté!sauce blanche grasse@sauce blanche grasse"
    "sauce@sauce!00grandes@*Grandes ---s de Base!veloute@Velouté"
    "きほんそーす@基本ソース!とりのうるて@鶏のヴルテ"
    "そーす@ソース!きほん@基本---!とりのうるて@鶏のヴルテ"
    "うるて@ヴルテ!とりのうるて@鶏の---（ヴルテドヴォライユ）"
    "そーす@ソース!うるてとり@ヴルテ（鶏）"
    "うおらいゆ@ヴォライユ!うるてとうおらいゆ@ヴルテドヴォライユ（鶏
のヴルテ）"
    "かきん@家禽!とりのうるて@鶏のヴルテ"
    "veloute@velouté!volaille@--- de Volaille"
    "sauce@sauce!veloute volaille@Velout\\'e de Volaille"
    "そーす@ソース!きほん@基本---!さかなりようりよううるて@魚料理用ヴルテ"
    "きほんそーす@基本ソース!さかなりようりよううるて@魚料理用ヴルテ"
    "うるて@ヴルテ!さかなうるて@魚料理用---"
    "そーす@ソース!う
るてさかな@ヴルテ(魚料理用)"
    "veloute@velouté!poisson@--- de
Poisson"
    "sauce@sauce!veloute poisson@Velouté de Poisson"
    "そーす@ソース!きほん@基本---!あるまんと@---・アルマンド"
    "きほんそーす@基本ソース!あるまんと@---・アルマンド"
    "そーす@ソース!ぱりふう@パリ風--- ⇒ ---・アルマンド"
    "はりふう@パリ風!そーす@---ソース ⇒ ---・アルマンド"
    "といつふう@ドイツ風!そーす@ソース・アルマンド（ドイツ風ソース）"
    "あるまん@アルマン（ド）!そーす@ソース・アルマンド"
    "sauce@sauce!00grandes@*Grandes ---s de Base!--- Allemande"
    "sauce@sauce!parisienne@--- parisienne (ex-Allemande)"
    "parisien@parisien!sauce@Sauce Parisienne = Sauce Allemande"
    "allemand@allemand!sauce@Sauce allemande (--- Parisienne)"
    "きほんそーす@基本ソース!しゆふれーむ@---・シュプレーム"
    "そーす@ソース!きほん@基本---!しゆふれーむ@---・シュプレーム"
    "そーす@ソース!そーすしゆふれーむ@---・シュプレーム"
    "しゆふれーむ@シュプレーム!そーす@ソース・---"
    "sauce@sauce!00grandes@*Grandes ---s de Base!supreme@--- Suprême"
    "sauce@sauce!supreme@--- Suprême"
    "supreme@suprême!sauce@Sauce ---"
    "きほんそーす@基本ソース!へしやめる@ベシャメル---"
    "そーす@ソース!きほん@基本---!へしやめる@ベシャメル---"
    "そーす@ソース!へしやめる@ベシャメル---"
    "へしやめる@ベシャメル!そーす@---ソース"
    "sauce@sauce!00grandes@*Grandes ---s de Base!bechamel@--- Béchamel"
    "sauce@sauce!bechamel@--- Béchamel"
    "bechamel@Béchamel (sauce)"
    "きほんそーす@基本ソース!とまと@トマト---"
    "そーす@ソース!きほん@基本---!とまと@トマト---"
    "そーす@ソース!とまとそーす@トマト---"
    "とまと@トマト!ソース@---ソース"
    "sauce@sauce!00grandes@*Grandes ---s de Base!tomate@--- tomate"
    "sauce@sauce!tomate@--- tomate"
    "tomate@tomate!sauce@Sauce ---"))
 :latex)

