(TeX-add-style-hook
 "01-01-pp1-12"
 (lambda ()
   (LaTeX-add-labels
    "sauces"
    "les-fonds-de-cuisine"
    "principaux-fonds-de-cuisine"
    "section-grandes-sauces-de-base"
    "osbservation-sur-la-sauce"
    "traitement-des-elements-de-base"
    "fonds-brun"
    "nota-fonds-brun"
    "fonds-blanc"
    "nota-fonds-blanc"
    "fonds-de-volaille"
    "jus-de-veau-brun"
    "fonds-de-gibier"
    "fumet-de-poisson"
    "nota-fumet-de-poisson"
    "fonds-de-poisson-au-vin-rouge"
    "nota-fonds-de-poisson-au-vin-rouge"
    "essence-de-poisson"
    "nota-essence-de-poisson"
    "essences-diverses"
    "glaces-diverses"
    "glace-de-viande"
    "nota-glace-de-viande"
    "glace-de-volaille"
    "glace-de-gibier"
    "glace-de-poisson"
    "roux"
    "roux-brun"
    "cuisson-des-roux"
    "nota-roux"
    "roux-blond"
    "roux-blanc")
   (LaTeX-add-index-entries
    "fonds@fonds"
    "ふおん@フォン"
    "そーす@ソース!きほん@基本---"
    "sauce@sauce!00grandes@*Grandes ---s de Base"
    "そーす@ソース!そーすつくりのべーす@---のベース作り"
    "sauce@sauce!Traitement des elements de base dans le travail des sauces@Traitement des Éléments de Base dans le Travail des ---s"
    "ふおん@フォン!ちやいろいふおん@茶色い---"
    "えすとうふあーと@エストゥファード"
    "fonds@fonds!brun@--- brun"
    "fonds@fonds!estouffade@estouffade (fonds brun)"
    "estouffade@estouffade!fonds brun@ --- (fonds brun)"
    "ふおん@フォン!しろい@白い---"
    "fonds@fonds!blanc ordinaire@--- blanc ordinaire"
    "ふおん@フォン!とりのふおん@鶏の---"
    "fonds@fonds!volaille@--- de volaille"
    "かきん@家禽!とりのふおん@鶏のフォン"
    "うおらいゆ@ヴォライユ!ふおんとうおらいゆ@フォンドヴォライユ"
    "ふおん@フォン!こうしのちやいろい@仔牛の茶色い---"
    "しゆ@ジュ!こうしのちやいろいしゆ@仔牛の茶色い---"
    "fonds@fonds!fonds de veau brun@--- de veau brun"
    "jus@jus!jus de veau brun@--- de veau brun"
    "こうし@仔牛!こうしのちやいろいふおん@---の茶色いフォン(ジュ)"
    "veau@veau!fonds brun@fonds ou jus de --- brun"
    "ふおん@フォン!しひえ@ジビエの---"
    "fonds@fonds!fonds de gibier@--- de gibier"
    "しひえ@ジビエ!ふおん@---のフォン"
    "gibier@gibier!fonds@fonds de ---"
    "ふおん@フォン!さかな@魚の---"
    "ふゆめ@フュメ!さかな@魚の---"
    "ふゆめ@フュメ!ほわそん@フュメドポワソン"
    "fumet@fumet!fumet de poisson@--- de poisson"
    "fonds@fonds!fumet de poisson@fumet de poisson"
    "ふおん@フォン!あかわいんをもちいたさかなのふおん@赤ワインを用いた魚の---"
    "fonds@fonds!fonds de poisson au vin rouge@--- de poisson au vin rouge"
    "えつせんす@エッセンス!さかな@魚の---"
    "essence@essence!poisson@--- de poisson"
    "えつせんす@エッセンス!01えつせんすについて@---について（フォン）"
    "essence@essence!01 diverses@---s diverses (fonds)"
    "くらす@グラス!01くらすについて@---について"
    "glace@glace!01 diverses@---s diverses"
    "くらす@グラス!くらすとういあんと@---ドヴィアンド"
    "glace@glace!viande@--- de viande"
    "くらす@グラス!とり@鶏の---（---ドヴォライユ）"
    "くらす@グラス!うおらいゆ@---ドヴォライユ"
    "glace@glace!volaille@--- de volaille"
    "くらす@グラス!しひえ@ジビエの---"
    "glace@glace!glace de gibier@--- de gibier"
    "しひえ@ジビエ!くらす@---のグラス"
    "gibier@gibier!gibier@glace de ---"
    "くらす@グラス!さかな@魚の---"
    "glace@glace!poisson@--- de poisson"
    "るー@ルー"
    "roux@roux"
    "るー@ルー!ちやいろ@茶色い---"
    "roux@roux!brun@--- brun"
    "るー@ルー!ひいれについて@---の火入れについて"
    "roux@roux!cuisson@cuisson du ---"
    "るー@ルー!ふろんと@ブロンドの---"
    "roux@roux!blond@--- blond"
    "るー@ルー!しろい@白い---"
    "roux@roux!blanc@--- blanc"))
 :latex)

