(TeX-add-style-hook
 "01-03-pp18-27"
 (lambda ()
   (LaTeX-add-labels
    "petites-sauces-brunes-composees"
    "sauce-bigarade"
    "sauce-bigarade-pour-caneton-braise"
    "sauce-bigarade-pour-caneton-poele"
    "sauce-bordelaise"
    "nota-sauce-bordelaise"
    "sauce-bourguignonne"
    "sauce-bretonne"
    "nota-sauce-bretonne"
    "sauce-aux-cerises"
    "sauce-aux-champignons"
    "sauce-charcutiere"
    "sauce-chasseur"
    "sauce-chasseur-procede-escoffier"
    "sauce-chaud-froid-brune"
    "sauce-chaud-froid-brune-pour-canards"
    "sauce-chaud-froid-brune-pour-gibier"
    "sauce-chaud-froid-tomatee"
    "sauce-chevreuil"
    "sauce-colbert"
    "sauce-diable"
    "nota-sauce-diable"
    "sauce-diable-escoffier"
    "sauce-diane"
    "sauce-duxelles"
    "nota-sauce-duxelles"
    "sauce-estragon"
    "sauce-financiere"
    "sauce-aux-fines-herbes"
    "nota-sauce-aux-fines-herbes"
    "sauce-genevoise"
    "nota-sauce-genevoise"
    "sauce-godard"
    "sauce-grand-veneur"
    "sauce-grand-veneur-procede-escoffier"
    "sauce-gratin"
    "sauce-hachee"
    "sauce-hachee-maigre"
    "sauce-hussarde"
    "sauce-italienne"
    "nota-sauce-italienne"
    "jus-lie-a-lestragon"
    "jus-lie-tomate"
    "sauce-lyonnaise"
    "nota-sauce-lyonnaise"
    "sauce-madere"
    "sauce-matelote"
    "sauce-moelle"
    "sauce-moscovite"
    "sauce-perigueux"
    "sauce-perigourdine"
    "sauce-piquante"
    "sauce-poivrade"
    "sauce-poivrade-pour-gibier"
    "nota-sauce-poivrade-pour-gibier"
    "sauce-au-porto"
    "sauce-portugaise"
    "sauce-provencale"
    "nota-sauce-provencale"
    "sauce-regence"
    "sauce-robert"
    "sauce-robert-escoffier"
    "sauce-romaine"
    "nota-sauce-romaine"
    "sauce-rouennaise"
    "sauce-salmis"
    "nota-sauce-salmis"
    "sauce-tortue"
    "nota-sauce-tortue"
    "sauce-venaison"
    "sauce-vin-rouge"
    "sauce-zingara-a"
    "sauce-zingara-b")
   (LaTeX-add-index-entries
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées"
    "そーす@ソース!ひからーと@---・ビガラード"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ひからーと@---・ビガラード"
    "ひからーと@ビガラード!そーす@ソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!bigarade@--- Bigarade"
    "sauce@sauce!bigarade@--- Bigarade"
    "bigarade@bigarade!sauce@Sauce ---"
    "そーす@ソース!ほるとーふう@ボルドー風---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ほるとーふう@ボルドー風---"
    "ほるとーふう@ボルドー風!そーす@---ソース"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!bordelaise@--- Bordelaise"
    "sauce@sauce!bordelaise@--- Bordelaise"
    "bordelais@bordelais(e)!sauce@Sauce Bordelaise"
    "そーす@ソース!ふるこーにゆふう@ブルゴーニュ風---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ふるこーにゆふう@ブルゴーニュ風---"
    "ふるこーにゆふう@ブルゴーニュ風!そーす@---ソース"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!bourguignonne@--- bourguignonne"
    "sauce@sauce!bourguignonne@--- Bourguignonne"
    "bourguignon@bourguignon(ne)!sauce@Sauce Bourguignonne"
    "そーす@ソース!ふるたーにゆふうふらうんけい@ブルターニュ風---（ブラウン系）"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ふるたーにゆふう@ブルターニュ風---"
    "ふるたーにゆふう@ブルターニュ風!そーすふらうんけい@---ソース（ブラウン系）"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!bretonne@--- Bretonne"
    "sauce@sauce!bretonne brune@--- Bretonne (brune)"
    "breton@breton(ne)!sauce brune@Sauce Bretonne (brune)"
    "そーす@ソース!すりーす@---・スリーズ"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!すりーす@---・スリーズ"
    "くろせいゆ@グロゼイユ!そーす@ソース!すりーす@---・スリーズ"
    "さくらんほ@サクランボ!そーす@ソース!すりーす@---・スリーズ"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!cerises@--- aux Cerises"
    "sauce@sauce!cerise@--- aux Cerises"
    "そーす@ソース!まつしゆるーむ@マッシュルーム ⇒ ---・シャンピニョン"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!しやんひによん@---・シャンピニョン"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!まつしゆるーむ@マッシュルーム ⇒ ---・シャンピニョン"
    "まっしゅるーむ@マッシュルーム ⇒ シャンピニョン"
    "しやんひによん@シャンピニョン!そーすふらうんけいはせい@ソース・---（ブラウン系）"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!champignons@--- aux Champignons"
    "sauce@sauce!champignons brune@--- aux Champignons (brune)"
    "champignon@champignon!sauce brune@Sauce aux Champignons (brune)"
    "そーす@ソース!しやるききゆとりふう@シャルキュトリ風 ⇒ ---・シャルキュティエール"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!しやるきゆていえーる@---・シャルキュティエール"
    "しやるきゆとりふう@シャルキュトリ風!そーす@---ソース ⇒ ソース・シャルキュティエール"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!charcutiere@--- Charcutière"
    "sauce@sauce!charcutiere@--- Charcutière"
    "charcutier@charcutier(ère)!sauce@Sauce Charcutière"
    "そーす@ソース!しやすーる@---・シャスール"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!しやすーる@---・シャスール"
    "しやすーる@シャスール!そーす@ソース・---"
    "かりうとふう@狩人風 ⇒ ソース・シャスール"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!chasseur@--- Chasseur"
    "sauce@sauce!chasseur@--- Chasseur"
    "chasseur@chasseur!sauce@Sauce ---"
    "そーす@ソース!しやすーるえすこふいえ@---・シャスール（エスコフィエ流）"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!しやすーるえすこふいえ@---・シャスール（エスコフィエ流）"
    "しやすーる@シャスール!そーすしゃすーるえすこふぃえ@ソース・---（エスコフィエ流）"
    "かりうとふう@狩人風 ⇒ ソース・シャスール（エスコフィエ流）"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!chasseur escoffier@--- Chasseur (Procédé Escoffier)"
    "sauce@sauce!chasseur escoffier@--- Chasseur (Procédé Escoffier)"
    "chasseur@chasseur!sauce escoffier@Sauce --- (Procédé Escoffier)"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!しよふろわちやいろ@茶色い---・ショフロワ（エスコフィエ流）"
    "そーす@ソース!しよふろわちやいろ@茶色い---・ショフロワ"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!しよふろわふらうんけい@茶色い---・ショフロワ"
    "しよふろわ@ショフロワ!そーすふらうんけい@茶色いソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!chaud-froid brune@--- Chaud-froid brune"
    "sauce@sauce!chaud-froid brune@--- Chaud-froid brune"
    "chaud-froid@chaud-froid!sauce brune@Sauce --- brune"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!しよふろわちやいろかもよう@茶色い---・ショフロワ（鴨用）"
    "そーす@ソース!しよふろわちやいと@茶色い---・ショフロワ（鴨用）"
    "しよふろわ@ショフロワ!ちやいろいそーすかもよう@茶色いソース・---（鴨用）"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!chaud-frois canard@--- Chaud-froid pouir Canards"
    "sauce@sauce!chaud-froid brune pour canards@--- Chaud-froid brune pour Canards"
    "chaud-froid@chaud-froid!sauce brune pour Canards@Sauce --- brune pour Canards"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!しよふろわちやいろしひえよう@茶色い---・ショフロワ（ジビエ用）"
    "そーす@ソース!しよふろわちやいろじびえよう@茶色い---・ショフロワ（ジビエ用）"
    "しよふろわ@ショフロワ!そーすしよふろわちやいろじびえよう@茶色いソース・---（ジビエ用）"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!chaud-frois gibier@--- Chaud-froid pour Gibier"
    "sauce@sauce!chaud-froid brune pour Gibier@--- Chaud-froid brune pour Gibier"
    "chaud-froid@chaud-froid!sauce brune pour Gibier@Sauce --- brune
pour Gibier"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!とまといりしよふろわ@トマト入り---・ショフロワ"
    "そーす@ソース!しよふろわとまといり@トマト入り---・ショフロワ"
    "しよふろわ@ショフロワ!そーすちやいろとまといり@トマト入りソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!chaud-froid tomatee@--- Chaud-froid tomatée"
    "sauce@sauce!chaud-froid tomatée@--- Chaud-froid tomatée"
    "chaud-froid@chaud-froid!sauce tomatée@Sauce --- tomatée"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!しゆうるいゆ@---・シュヴルイユ"
    "しゆうるいゆ@シュヴルイユ!そーす@ソース・---"
    "そーす@ソース!しゅうるいゆ@---・シュヴルイユ"
    "のろしか@ノロ鹿 ⇒ シュヴルイユ!そーす@ソース!しゆうるいゆ@ソース・シュヴルイユ"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!chevreuil@--- Chevreuil"
    "sauce@sauce!chevreuil@--- Chevreuil"
    "chevreuil@chevreuil!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!こるへーる@---・コルベール"
    "そーす@ソース!こるへーる@---・コルベール"
    "こるへーる@コルベール!そーす@ソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!colbert@--- Colbert"
    "sauce@sauce!colbert@--- Colbert"
    "colbert@Colbert!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ていあーふる@---・ディアーブル"
    "そーす@ソース!ていあーふる@---・ディアーブル"
    "ていあーふる@ディアーブル!そーす@ソース・---"
    "あくま@悪魔 ⇒ ディアーブル!そーす@ソース!そーすていあーふる@ソース・ディアーブル"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!diable@--- Diable"
    "sauce@sauce!diable@--- Diable"
    "diable@diable!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ていあーふるえすこふいえ@---・ディアーブル・エスコフィエ"
    "そーす@ソース!ていあーふるえすこふいえ@---・ディアーブル・エスコフィエ"
    "ていあーふる@ディアーブル!そーす@ソース!えすこふいえ@ソース・---・エスコフィエ"
    "あくま@悪魔 ⇒ ディアーブル!そーす@ソース!エスコフイエ@ソース・ディアーブル・エスコフィエ"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!diable escoffier@--- Diable Escoffier"
    "sauce@sauce!diable escoffier@--- Diable Escoffier"
    "diable@diable!sauce escoffier@Sauce --- Escoffier"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ていあーぬ@---・ディアーヌ"
    "そーす@ソース!ていあーぬ@---・ディアーヌ"
    "ていあーぬ@ディアーヌ!そーす@ソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!diane@--- Diane"
    "sauce@sauce!diane@--- Diane"
    "diane@Diane!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!てゆくせる@---・デュクセル"
    "そーす@ソース!てゆくせる@---・デュクセル"
    "てゆくせる@デュクセル!そーす@ソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!duxelles@--- Duxelles"
    "sauce@sauce!duxelles@--- Duxelles"
    "duxelles@duxelles!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!えすとらこん@---・エストラゴン"
    "そーす@ソース!えすとらこんちゃいろ@---・エストラゴン（ブラウン系）"
    "えすとらこん@エストラゴン!そーすふらうんけい@ソース・---（ブラウン系）"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!estragon@--- Estragon"
    "sauce@sauce!estragon brune@--- Estragon (brune)"
    "estragon@estragon!sauce brune@Sauce --- (brune)"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ふいなんしえーる@---・フィナンシエール"
    "そーす@ソース!ふいなんしえーる@---・フィナンシエール"
    "ふいなんしえーる@フィナンシエール!そーす@ソース・---"
    "ちょうせいかんふう@徴税官風 ⇒ フィナンシエール!そーすふぃなんしえーる@ソース・フィナンシエール"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!financiere@--- Financière"
    "sauce@sauce!financiere@--- Financière"
    "financier@financier(ère)!sauce@Sauce Financière"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!こうそう@香草---"
    "そーす@ソース!こうそうふらうんけい@香草---（ブラウン系）"
    "こうそう@香草!そーすふらうんけい@---ソース（ブラウン系）"
    "はーぶ@ハーブ ⇒ 香草!こうそうそーすふらうんけい@香草ソース（ブラウン系）"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!fines herbes@--- aux Fines Herbes"
    "sauce@sauce!fines herbes@--- aux Fines Herbes"
    "fines
herbes@fines herbes!sauce@Sauce aux ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!しゆねーうふう@ジュネーヴ風---"
    "そーす@ソース!しゆねーうふう@ジュネーヴ風---"
    "しゆねーうふう@ジュネーヴ風!そーす@---ソース"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!genevoise@--- Genevoise"
    "sauce@sauce!genevoise@--- Genevoise"
    "genevois@genevois(e)!sauce@Sauce Genevoise"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!こたーる@---・ゴダール"
    "そーす@ソース!こたーる@---・ゴダール"
    "こたーる@ゴダール!そーす@ソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!godard@--- Godard"
    "sauce@sauce!godard@--- Godard"
    "godard@Godard!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!くらんうぬーる@---・グランヴヌール"
    "そーす@ソース!くらんうぬーる@---・グランヴヌール"
    "くらんうぬーる@グランヴヌール!そーす@ソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!grand-veneur@--- Grand-Veneur"
    "sauce@sauce!grand-veneur@--- Grand-Veneur"
    "grand-veneur@grand-veneur!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!くらんうぬーるえすこふいえ@---・グランヴヌール（エスコフィエ流）"
    "そーす@ソース!くらんうぬーるえすこふいえ@---・グランヴヌール（エスコフィエ流）"
    "くらんうぬーる@グランヴヌール!そーすえすこふいえ@ソース・---（エスコフィエ流）"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!grand-veneur escoffier@--- Grand-Veneur (Procédé Escoffier)"
    "sauce@sauce!grand-veneur escoffier@--- Grand-Veneur (Procédé Escoffier)"
    "grand-veneur@grand-veneur!sauce escoffier@Sauce --- (Procédé Escoffier)"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!くらたん@---・グラタン"
    "そーす@ソース!くらたん@---・グラタン"
    "くらたん@グラタン!そーす@ソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!gratin@--- Gratin"
    "sauce@sauce!gratin@--- Gratin"
    "gratin@gratin!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!あしえ@---・アシェ"
    "そーす@ソース!あしえ@---・アシェ"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!hachee@--- Hachée"
    "sauce@sauce!hachee@--- Hachée"
    "hache@haché(e)!sauce@Sauce Hachée"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!あしえさかな@魚料理用---・アシェ"
    "そーす@ソース!あしえ@魚料理用---・アシェ"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!hachee maigre@--- Hachée maigre"
    "sauce@sauce!hachee maigre@--- Hachée maigre"
    "hache@haché(e)!sauce maigre@Sauce Hachée maigre"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ゆさると@---・ユサルド"
    "そーす@ソース!ゆさると@---・ユサルド"
    "ゆさると@ユサルド!そーす@ソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!hussarde@--- Hussarde"
    "sauce@sauce!hussarde@--- Hussarde"
    "hussard@Hussard(e)!sauce@Sauce Hussarde"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!イタリア風@---"
    "そーす@ソース!いたりあふう@イタリア風---"
    "いたりあふう@イタリア風!そーす@---ソース"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!italienne@--- Italienne"
    "sauce@sauce!Italienne@--- Italienne"
    "italien@italien(ne)!sauce@Sauce Italienne"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!とろみをつけたしゆえすとらこん@とろみを付けたジュ　エストラゴン風味"
    "そーす@ソース!とろみをつけたしゆえすとらこん@とろみを付けたジュエストラゴン風味"
    "しゆ@ジュ!とろみをつけたえすとらごん@とろみを付けた---　エストラゴン風味"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!jus lie estragon@Jus lié à l'estragon"
    "sauce@sauce!jus lie estragon@Jus lié à l'Estragon"
    "estragon@estragon!jus lie estragon@Jus lié à l'Estragon"
    "jus@jus!lie estragon@--- lié à l'Estragon"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!とろみをつけたしゆとまとふうみ@とろみを付けたジュ　トマト風味"
    "そーす@ソース!とろみをつけたしゆとまと@とろみを付けたジュ　トマト風味"
    "しゆ@ジュ!とろみをつけたとまとふうみ@とろみを付けた---　トマト風味"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!jus lie tomatee@Jus lié tomatée"
    "sauce@sauce!jus lie tomatee@Jus lié tomaté"
    "tomate@tomate!jus lie tomate@Jus lié tomaté"
    "jus@jus!lie tomate@--- lié tomaté"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!りよんふう@リヨン風---"
    "そーす@ソース!りよんふう@リヨン風---"
    "りよんふう@リヨン風!そーす@---ソース"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!lyonnaise@--- Lyonnaise"
    "sauce@sauce!lyonnaise@--- Lyonnaise"
    "liyonnais@lyonnais(e)!sauce lyonnaise@Sauce Lyonnaise"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!まてーる@---・マデール"
    "そーす@ソース!までーる@---・マデール"
    "まてらしゆ@マデイラ酒 ⇒ マデール!そーす@ソース・マデール"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!madere@--- Madère"
    "sauce@sauce!madere@--- Madère"
    "madere@madère!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!まとろつと@---・マトロット"
    "そーす@ソース!まとろつと@---・マトロット"
    "まとろつと@マトロット!そーす@ソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!matelote@--- Matelote"
    "sauce@sauce!matelote@--- Matelote"
    "matelote@matelote!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!もわる@---・モワル"
    "そーす@ソース!もわる@---・モワル"
    "こつずい@骨髄 ⇒ モワル!そーすもわる@ソース・モワル"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!moelle@--- Moelle"
    "sauce@sauce!moelle@--- Moelle"
    "moelle@moelle!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!もすくわふう@モスクワ---"
    "そーす@ソース!もすくわふう@モスクワ風---"
    "もすくわふう@モスクワ風!そーす@---ソース"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!moscovite@--- Moscovite"
    "sauce@sauce!moscovite@--- Moscovite"
    "moscovite@moscovite!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!へりくー@---・ペリグー"
    "そーす@ソース!へりくー@---・ペリグー"
    "へりくー@ペリグー!そーす@ソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!perigueux@--- Périgueux"
    "sauce@sauce!perigueux@--- Périgueux"
    "perigueux@Périgueux!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!へりくるていーぬ@---・ペリグルディーヌ"
    "そーす@ソース!へりくるていーぬ@---・ペリグゥルディーヌ"
    "へりこーるふう@ペリゴール風 ⇒ ペリグルダン/ペリグルディーヌ!そーす@ソース・ペリグルディーヌ"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!perigourdine@--- Périgourdine"
    "sauce@sauce!perigourdine@--- Périgourdine"
    "perigourdin@périgourdin(e)!sauce@Sauce Périgourdine"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ひかんと@---・ピカント"
    "そーす@ソース!ひかんと@---・ピカント"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!piquante@--- piquante"
    "sauce@sauce!piquante@--- Piquante"
    "piquant@piquant(e)!sauce@Sauce Piquante"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ほわうらーと@---・ポワヴラード（標準）"
    "そーす@ソース!ほわうらーと@---・ポワヴラード（標準）"
    "ほわうらーと@ポワヴラード!そーす@ソース・---（標準）"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!poivrade ordinaire@--- Poivrade"
    "sauce@sauce!poivrade ordinaire@--- Poivrade ordinaire"
    "poivrade@poivrade!sauce ordinaire@Sauce --- ordinaire"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ほわうらーとしひえ@---・ポワヴラード（ジビエ用）"
    "そーす@ソース!ほわうらーとしひえ@---・ポワヴラード（ジビエ用）"
    "ほわうらーと@ポワヴラード!そーすしひえ@ソース・---（ジビエ用）"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!poivrade gibier@--- Poivrade pour Gibier"
    "sauce@sauce!poivrade gibier@--- Poivrade pour Gibier"
    "poivrade@poivrade!sauce  gibier@Sauce --- pour Gibier"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ほると@---・ポルト"
    "そーす@ソース!ほると@---・ポルト"
    "ほるとしゆ@ポルト酒 ⇒ ポルト!そーす@ソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!porto@--- Porto"
    "sauce@sauce!porto@--- au Porto"
    "porto@Porto!sauce@Sauce au ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ほるとかるふう@ポルトガル風---"
    "そーす@ソース!ほるとかるふう@ポルトガル風---"
    "ほるとかるふう@ポルトガル風!そーす@---ソース"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!portugaise@--- Portugaise"
    "sauce@sauce!porugaise@--- Portugaise"
    "portugais@portugais(e)!sauce@Sauce Portugaise"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ふろうあんすふう@プロヴァンス風---"
    "そーす@ソース!ふろうあんすふう@プロヴァンス風---"
    "ふろうあんすふう@プロヴァンス風!そーす@---ソース"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!provencale@--- Provençale"
    "sauce@sauce!provencale@--- Provençale"
    "provencal@provençal(e)!sauce@Sauce Provençale"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!れしやんす@---・レジャンス"
    "そーす@ソース!れしやんす@---・レジャンス"
    "れしやんす@レジャンス!そーす@ソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!regence@--- Régence"
    "sauce@sauce!regence@--- Régence"
    "regence@Régence!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ろへーる@---・ロベール"
    "そーす@ソース!ろへーる@---・ロベール"
    "ろへーる@ロベール!そーす@ソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!Robert@--- Robert"
    "sauce@sauce!robert@--- Robert"
    "robert@Robert!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ろへーるえすこふいえ@---・ロベール・エスコフィエ"
    "そーす@ソース!ろへーるえすこふいえ@---・ロベール・エスコフィエ"
    "ろへーる@ロベール!そーすえすこふいえ@ソース・---・エスコフィエ"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!robert escoffier@--- Robert Escoffier"
    "sauce@sauce!robert escoffier@--- Robert Escoffier"
    "robert@Robert!sauce escoffier@Sauce --- Escoffier"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!ろーまふう@ローマ風---"
    "そーす@ソース!ろーまふう@ローマ風---"
    "ろーまふう@ローマ風!そーす@---ソース"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!romaine@--- Romaine"
    "sauce@sauce!romain@--- Romaine"
    "romain@romain(e)!Sauce Romaine"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!るーあんふう@ルーアン風---"
    "そーす@ソース!るーあんふう@ルーアン風---"
    "るーあんふう@ルーアン風!そーす@---ソース"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!rouannaise@--- Rouannaise"
    "sauce@sauce!rouannaise@--- Rouannaise"
    "rouannais@rouannais(e)!sauce@Sauce Rouannaise"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!さるみ@---・サルミ"
    "そーす@ソース!さるみ@---・サルミ"
    "さるみ@サルミ!そーす@ソース・---"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!salmis@--- Salmis"
    "sauce@sauce!salmis@--- Salmis"
    "salmis@salmis!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!とるちゆ@---・トルチュ"
    "そーす@ソース!とるちゅ@---・トルチュ"
    "とるちゅ@トルチュ!そーす@ソース・---"
    "うみかめ@海亀 ⇒ トルチュ!そーすとるちゆ@ソース・トルチュ"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!tortue@--- Tortue"
    "sauce@sauce!tortue@--- Tortue"
    "tortue@tortue!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!うねそん@---・ヴネゾン"
    "そーす@ソース!うねそん@---・ヴネゾン"
    "うねそん@ヴネゾン!そーす@ソース・---"
    "おおかたしひえ@大型ジビエ ⇒ ヴネゾン!そーす@ソース・ヴネゾン"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!venaison@--- Venaison"
    "sauce@sauce!venaison@--- Venaison"
    "venaison@venaison!sauce@Sauce ---"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!あかわいん@赤ワイン---"
    "そーす@ソース!あかわいん@赤ワイン---"
    "あかわいん@赤ワイン!そーす@---ソース"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!vin rouge@--- au Vin rouge"
    "sauce@sauce!vin rouge@--- au Vin rouge"
    "vin@vin!sauce rouge@Sauce au --- rouge"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!さんからa@---・ザンガラA"
    "そーす@ソース!さんからa@---・ザンガラ A"
    "さんから@ザンガラ!そーすa@ソース・--- A"
    "しふしーふう@ジプシー風!そーすa@ソース・ザンガラ A"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!zingara a@--- Zingara A"
    "sauce@sauce!zingara a@--- Zingara A"
    "zingara@Zingara!sauce a@Sauce --- A"
    "そーす@ソース!ふらうんはせい@ブラウン系の派生---!さんからb@---・ザンガラB"
    "そーす@ソース!さんからb@---・ザンガラ B"
    "さんから@ザンガラ!そーすb@ソース・--- B"
    "しふしーふう@ジプシー風!そーすb@ソース・ザンガラ B"
    "sauce@sauce!petites brunes composees@Petites ---s Brunes Composées!zingara b@--- Zingara B"
    "sauce@sauce!zingara b@--- Zingara B"
    "zingara@Zingara!sauce b@Sauce --- B"))
 :latex)

