(TeX-add-style-hook
 "01-07-pp53-57"
 (lambda ()
   (LaTeX-add-labels
    "beurres-composes"
    "observation-sur-les-beurres-composes"
    "beurre-d-ail"
    "beurre-d-anchois"
    "beurre-d-amande"
    "ux30d6ux30fcux30ebux30c0ux30f4ux30eaux30fcux30cc8"
    "beurre-d-aveline"
    "beurre-bercy"
    "beurre-de-caviar"
    "beurre-chivry"
    "beurre-colbert"
    "beurre-colorant-rouge"
    "nota-beurre-colorant-rouge"
    "beurre-colorant-vert"
    "nota-beurre-colorant-vert"
    "beurre-de-crevettes"
    "beurre-d-echalote"
    "beurre-d-ecrevisse"
    "beurre-pour-les-escargots"
    "beurre-d-estragon"
    "beurre-de-hereng"
    "beurre-de-homard"
    "beurre-de-laitance"
    "beurre-maitre-d-hotel"
    "nota-beurre-maitre-d-hotel"
    "beurre-manie"
    "beurre-marchand-de-vin"
    "beurre-a-la-meuniere"
    "beurre-de-montpellier"
    "beurre-de-montpellier-pour-croutonnage-de-plats"
    "beurre-de-moutarde"
    "beurre-noir-pour-les-grands-services"
    "beurre-de-noisette"
    "beurre-de-paprika"
    "beurre-de-pimentos"
    "beurre-de-pistache"
    "beurre-a-la-polonaise"
    "beurre-de-raifort"
    "beurre-ravigote"
    "beurre-de-saumon-fume"
    "beurre-de-truffe"
    "beurres-printaniers"
    "coulis-divers"
    "huile-de-crustaces")
   (LaTeX-add-index-entries
    "あわせはたー@合わせバター"
    "はたー@バター ⇒ 合わせバター"
    "ふーるこんほせ@ブール・コンポゼ ⇒ 合わせバター"
    "みつくすはたー@ミックスバター ⇒ 合わせバター"
    "beurre@beurre!beurres composes@Beurres Composés"
    "はたー@バター!あわせはたー@合わせバター!にんにくはたー@にんにくバター"
    "あわせはたー@合わせバター!にんにくはたー@にんにくバター"
    "にんにく@にんにく!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre d'ail@Beurre d'Ail"
    "ail@ail!beurre@Beurre d'---"
    "はたー@バター!あわせはたー@合わせバター!あんちよひはたー@アンチョビバター"
    "あわせはたー@合わせバター!あんちよひはたー@アンチョビバター"
    "あんちよひ@アンチョビ!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre d'anchois@Beurre d'Anchois"
    "anchois@anchois!beurre@Beurre d'---"
    "はたー@バター!あわせはたー@合わせバター!あーもんとはたー@アーモンドバター"
    "あわせはたー@合わせバター!あーもんとはたー@アーモンドバター"
    "あーもんと@アーモンド!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre d'amande@Beurre d'Amande"
    "amande@amande!beurre@Beurre d'---"
    "はたー@バター!あわせはたー@合わせバター!ふーるたうりーぬ@ブール・ダヴリーヌ"
    "あわせはたー@合わせバター!ふーるたうりーぬ@ブール・ダヴリーヌ"
    "あうりーぬ@アヴリーヌ!ふーる@ブール・---"
    "へーせるなつつ@ヘーゼルナッツ!ふーるたうりーぬ@ブール・ダヴリーヌ"
    "beurre@beurre!beurres composes@Beurres Composés!beurre d'aveline@Beurre d'Aveline"
    "aveline@aveline!beurre@Beurre d'---"
    "はたー@バター!あわせはたー@合わせバター!ふーるへるしー@ブール・ベルシー"
    "あわせはたー@合わせバター!ふーるたへるしー@ブール・ベルシー"
    "へるしー@ベルシー!ふーる@ブール・---"
    "beurre@beurre!beurres composes@Beurres Composés!beurre bercy@Beurre Bercy"
    "bercy@Bercy!beurre@Beurre ---"
    "はたー@バター!あわせはたー@合わせバター!きやひあはたー@キャビアバター"
    "あわせはたー@合わせバター!きやひあはたー@キャビアバター"
    "きやひあ@キャビア!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre caviar@Beurre de Caviar"
    "caviar@caviar!beurre@Beurre de ---"
    "はたー@バター!あわせはたー@合わせバター!しうり@ブール・シヴリ"
    "あわせはたー@合わせバター!しうり@ブール・シヴリ"
    "はたー@バター!あわせはたー@合わせバター!らういこつと@ブール・ラヴィゴット"
    "あわせはたー@合わせバター!らういこつと@ブール・ラヴィゴット"
    "しうり@シヴリ!ふーる@ブール・---"
    "らういこつと@ラヴィゴット!ふーる@ブール・---"
    "beurre@beurre!beurres composes@Beurres Composés!beurre chivry@Beurre Chivrya"
    "beurre@beurre!beurres composes@Beurres Composés!beurre ravigote@Beurre Ravigote"
    "chivry@Chivry!beurre@Beurre ---"
    "ravigote@ravitote!beurre@Beurre ---"
    "はたー@バター!あわせはたー@合わせバター!ふーるこるへーる@ブール・コルベール"
    "あわせはたー@合わせバター!ふーるこるへーる@ブール・コルベール"
    "こるへーる@コルベール!ふーる@ブール・---"
    "beurre@beurre!beurres composes@Beurres Composés!beurre colbert@Beurre Colbert"
    "colbert@Colbert!beurre@Beurre ---"
    "はたー@バター!あわせはたー@合わせバター!いろつけようのあかいはたー@色付け用の赤いバター"
    "あわせはたー@合わせバター!いろつけようのあかいはたー@色付け用の赤いバター"
    "ちやくしよくそざい@着色素材!いろつけようのあかいはたー@色付け用の赤いバター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre colorant rouge@Beurre Colorant rouge"
    "colorant@colorant!beurre rouge@Beurre --- rouge"
    "はたー@バター!あわせはたー@合わせバター!いろつけようのみとりのはたー@色付け用の緑のバター"
    "あわせはたー@合わせバター!いろつけようのみとりのはたー@色付け用の緑のバター"
    "ちやくしよくそざい@着色素材!いろつけようのみとりのはたー@色付け用の緑のバター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre colorant vert@Beurre Colorant vert"
    "colorant@colorant!beurre vert@Beurre --- vert"
    "はたー@バター!あわせはたー@合わせバター!くるうえつとはたー@クルヴェットバター"
    "あわせはたー@合わせバター!くるうえつとはたー@クルヴェットバター"
    "くるうえつと@クルヴェット!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre crevette@Beurre de Crevette"
    "crevette@crevette!beurre@Beurre de ---"
    "はたー@バター!あわせはたー@合わせバター!えしやろつとはたー@エシャロットバター"
    "あわせはたー@合わせバター!えしやろつとはたー@エシャロットバター"
    "えしやろつと@エシャロット!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre echalote@Beurre d'Echalote"
    "echalote@echalote!beurre@Beurre de ---"
    "はたー@バター!あわせはたー@合わせバター!えくるういすはたー@エクルヴィスバター"
    "あわせはたー@合わせバター!えくるういすはたー@エクルヴィスバター"
    "えくるういす@エクルヴィス!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre ecrevisse@Beurre d'Ecrevisse"
    "ecrevisse@ecrevisse!beurre@Beurre d'---"
    "はたー@バター!あわせはたー@合わせバター!えすかるこようはたー@エスカルゴ用バター"
    "あわせはたー@合わせバター!えすかるこようはたー@エスカルゴ用バター"
    "えすかるこ@エスカルゴ!はたー@---用バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre escargots@Beurre pour les Escargots"
    "escargot@escargot!beurre@Beurre pour les ---"
    "はたー@バター!あわせはたー@合わせバター!えすとらこんはたー@エストラゴンバター"
    "あわせはたー@合わせバター!えすとらこんはたー@エストラゴンバター"
    "えすとらこん@エストラゴン!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre estragon@Beurre d'Estragon"
    "estragon@estragon!beurre@Beurre d'---"
    "はたー@バター!あわせはたー@合わせバター!にしんはたー@にしんバター"
    "あわせはたー@合わせバター!にしんはたー@にしんバター"
    "にしん@にしん!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre hareng@Beurre de Hareng"
    "hareng@hareng!beurre@Beurre de ---"
    "はたー@バター!あわせはたー@合わせバター!おまーるはたー@オマールバター"
    "あわせはたー@合わせバター!おまーるはたー@オマールバター"
    "おまーる@オマール!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre homard@Beurre de Homard"
    "homard@homard!beurre@Beurre de ---"
    "はたー@バター!あわせはたー@合わせバター!しらこはたー@白子バター"
    "あわせはたー@合わせバター!しらこはたー@白子バター"
    "しらこ@白子!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre laitance@Beurre de Laitance"
    "laitance@laitance!beurre@Beurre de ---"
    "はたー@バター!あわせはたー@合わせバター!めとるとてるはたー@メートルドテルバター"
    "あわせはたー@合わせバター!めーとるとてるはたー@メートルドテルバター"
    "めーとるとてる@メートルドテル!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre maitre hotel@Beurre à la Maître d'hôtel"
    "maitre hotel@maître d'hôtel!beurre@Beurre à la ---"
    "はたー@バター!あわせはたー@合わせバター!ふーるまにえ@ブールマニエ"
    "あわせはたー@合わせバター!ふーるまにえ@ブールマニエ"
    "ふーるまにえ@ブールマニエ"
    "beurre@beurre!beurres composes@Beurres Composés!beurre manie@Beurre Manié"
    "beurre manie@beurre manié"
    "はたー@バター!あわせはたー@合わせバター!ふーるまるしやんとうあん@ブール・マルシャンドヴァン"
    "あわせはたー@合わせバター!ふーるまるしやんとうあん@ブール・マルシャンドヴァン"
    "わいんしようにん@ワイン商人 ⇒ マルシャンドヴァン!ふーる@ブール・マルシャンドヴァン"
    "まるしやんとうあん@マルシャンドヴァン!ふーる@ブール・マルシャンドヴァン"
    "beurre@beurre!beurres composes@Beurres Composés!beurre marchand vin@Beurre Marchand de vin"
    "marchand vin@marcand de vin!beurre@Beurre ---"
    "はたー@バター!あわせはたー@合わせバター!むにえるようはたー@ムニエル用バター"
    "あわせはたー@合わせバター!むにえるようはたー@ムニエル用バター"
    "むにえる@ムニエル!はたー@---用バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre meuniere@Beurre à la Meunière"
    "meuniere@meunière (à la)!beurre@Beurre à la ---"
    "はたー@バター!あわせはたー@合わせバター!もんへりえはたー@モンペリエバター"
    "あわせはたー@合わせバター!もんへりえはたー@モンペリエバター"
    "もんへりえ@モンペリエ!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre monpellier@Beurre de Montpellier"
    "montepellier@Montpellier!beurre@Beurre de ---"
    "はたー@バター!あわせはたー@合わせバター!そうしよくようもんへりえはたー@装飾用モンペリエバター"
    "あわせはたー@合わせバター!そうしよくようもんへりえはたー@装飾用モンペリエバター"
    "もんへりえ@モンペリエ!そうしよくようはたー@装飾用---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre meuniere cretonnage@Beurre de Montpellier pour croûtonnage de plats"
    "montepellier@Montpellier!beurre cretonnage@Beurre de --- pour Croûtonnage de plats"
    "はたー@バター!あわせはたー@合わせバター!ますたーとはたー@マスタードバター"
    "あわせはたー@合わせバター!ますたーとはたー@マスタードバター"
    "ますたーと@マスタード!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre moutarde@Beurre de Moutarde"
    "moutarde@moutarde!beurre@Beurre de ---"
    "はたー@バター!あわせはたー@合わせバター!かくしきあるえんせきようこかしはたー@格式ある宴席用焦がしバター"
    "あわせはたー@合わせバター!かくしきあるえんせきようこかしはたー@格式ある宴席用焦がしバター"
    "くろ@黒!はたー@---バター"
    "はたー@バター!こかし@焦がし---"
    "beurre@beurre!beurres composes@Beurres Composés!beurre noir grands services@Beurre noir pour les grands services"
    "noir@noir!beurre@Beurre --- pour les grands services"
    "はたー@バター!あわせはたー@合わせバター!ふーるとのわせつと@ブール・ド・ノワゼット"
    "あわせはたー@合わせバター!ふーるとのわせつと@ブール・ド・ノワゼット"
    "のわせつと@ノワゼット!ふーるとのわせつと@ブール・ド・---"
    "beurre@beurre!beurres composes@Beurres Composés!beurre noisette@Beurre de noisette"
    "noisette@noisette!beurre@Beurre de ---"
    "はたー@バター!あわせはたー@合わせバター!はふりかはたー@パプリカバター"
    "あわせはたー@合わせバター!はふりかはたー@パプリカバター"
    "はふりか@パプリカ!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre  Paprika@Beurre de Paprika"
    "paprika@paprika!beurre@Beurre de ---"
    "はたー@バター!あわせはたー@合わせバター!あかひーまんはたー@赤ピーマンバター"
    "あわせはたー@合わせバター!あかひーまんはたー@赤ピーマンパプリカバター"
    "あかひーまん@赤ピーマン!はたー@---バター"
    "ほわうろん@ポワヴロン ⇒ 赤ピーマン"
    "beurre@beurre!beurres composes@Beurres Composés!beurre pimentos@Beurre de Pimentos"
    "pimentos@pimentos!beurre@Beurre de ---"
    "poivron@poivron!beurre pimentos!Beurre de Pimentos"
    "はたー@バター!あわせはたー@合わせバター!ひすたちおはたー@ピスタチオバター"
    "あわせはたー@合わせバター!ひすたちおはたー@ピスタチオバター"
    "ひすたちお@ピスタチオ!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre pistache@Beurre de Pistache"
    "pistache@pistache!beurre@Beurre de ---"
    "はたー@バター!あわせはたー@合わせバター!ほーらんとふうはたー@ポーランド風バター"
    "あわせはたー@合わせバター!ほーらんとふうはたー@ポーランド風バター"
    "ポーランド@ポーランド!はたー@---風バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre polonaise@Beurre à la Polonaise"
    "polonais@polonais(e)!beurre@Beurre à la ---e"
    "はたー@バター!あわせはたー@合わせバター!れふおーるはたー@レフォールバター"
    "あわせはたー@合わせバター!れふおーる@レフォールバター"
    "れふおーる@レフォール!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre raifort@Beurre de Raifort"
    "raifort@raifort!beurre@Beurre de ---"
    "はたー@バター!あわせはたー@合わせバター!うえーる@ブール・ヴェール"
    "あわせはたー@合わせバター!うえーる@ブール・ヴェール"
    "みどり@緑 ⇒ ヴェール"
    "beurre@beurre!beurres composes@Beurres Composés!beurre vert@Beurre vert"
    "ravigote@ravigote!beurre@Beurre ---"
    "vert@vert(e)!beurre@Beurre ---"
    "はたー@バター!あわせはたー@合わせバター!すもーくさーもんはたー@スモークサーモンバター"
    "あわせはたー@合わせバター!すもーくさーもん@スモークサーモンバター"
    "すもーくさーもん@スモークサーモン!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre saumon fumet@Beurre de Saumon fumé"
    "saumon fume@saumon fumé!beurre@Beurre de ---"
    "はたー@バター!あわせはたー@合わせバター!とりゆふはたー@トリュフバター"
    "あわせはたー@合わせバター!とりゆふ@トリュフバター"
    "とりゆふ@トリュフ!はたー@---バター"
    "beurre@beurre!beurres composes@Beurres Composés!beurre truffe@Beurre de Truffe"
    "truffe@truffe!beurre@Beurre de ---"
    "はたー@バター!あわせはたー@合わせバター!ふーるふらんたにえ@ブール・プランタニエ"
    "あわせはたー@合わせバター!ふーるとふらんたにえ@ブール・プランタニエ"
    "ふらんたにえ@プランタニエ!ふーる@ブール・---"
    "beurre@beurre!beurres composes@Beurres Composés!beurres printaniers@Beurres Printaniers"
    "printanier@printanier(ère)!beurre@Beurres Printaniers"
    "はたー@バター!あわせはたー@合わせバター!くりかくしゆ@クリ各種"
    "あわせはたー@合わせバター!くりかくしゆ@クリ各種"
    "くり@クリ!はたー@クリ各種"
    "beurre@beurre!beurres composes@Beurres Composés!coulis divers@Coulis divers"
    "coulis@coulis!beurre@Coulis divers"
    "はたー@バター!あわせはたー@合わせバター!こうかくるいのおいる@甲殻類のオイル"
    "あわせはたー@合わせバター!こうかくるいのおいる@甲殻類のオイル"
    "こうかくるい@甲殻類!はたー@甲殻類のオイル"
    "beurre@beurre!beurres composes@Beurres Composés!huile crustaces@Huile de Crustacés"
    "crustace@crustace!huile@Huile de ---s"))
 :latex)

