(TeX-add-style-hook
 "01-04-pp28-41"
 (lambda ()
   (LaTeX-add-labels
    "petites-sauces-blanches"
    "sauce-albufera"
    "sauce-americaine"
    "sauce-anchois"
    "sauce-aurore"
    "sauce-aurore-maigre"
    "sauce-bavaroise"
    "sauce-bearnaise"
    "nota-sauce-bearnaise"
    "sauce-bearnaise-tomatee"
    "sauce-bearnaise-a-la-glace-de-viande"
    "sauce-bercy"
    "sauce-au-beurre"
    "nota-sauce-au-beurre"
    "sauce-bonnefoy"
    "sauce-bretonne-blanche"
    "sauce-canotiere"
    "nota-sauce-canotiere"
    "sauce-aux-capres"
    "sauce-cardinal"
    "sauce-aux-champignons-blanche"
    "sauce-chantilly"
    "sauce-chateaubriand"
    "sauce-chaud-froid-blanche-ordinaire"
    "sauce-chaud-froid-blonde"
    "sauce-chaud-froid-aurore"
    "nota-sauce-chaud-froid-aurore"
    "sauce-choud-froid-vert-pre"
    "sauce-chaud-froid-maigre"
    "nota-sauce-chaud-froid-maigre"
    "sacue-chivry"
    "nota-sauce-chivry"
    "sauce-choron"
    "sauce-creme"
    "sauce-aux-crevettes"
    "sauce-currie"
    "nota-sauce-currie"
    "sauce-currie-indienne"
    "nota-sauce-currie-indienne"
    "sauce-diplomate"
    "sauce-ecossaise"
    "sauce-estragon-blanche"
    "sauce-aux-fines-herbes-blanche"
    "sauce-foyot"
    "sauce-groseilles"
    "nota-sauce-groseiles"
    "sauce-hollandaise"
    "nota-sauce-hollandaise"
    "sauce-homard"
    "nota-sauce-homard"
    "sauce-hongroise"
    "sauce-aux-huitres"
    "sauceindienne"
    "sauce-ivoire"
    "sauce-joinville"
    "nota-sauce-joinville"
    "sauce-laguipiere"
    "nota-sauce-laguipiere"
    "sauce-livonienne"
    "sauce-maltaise"
    "sauce-mariniere"
    "sauce-matelote-blanche"
    "sauce-mornay"
    "nota-sauce-mornay"
    "sauce-mousseline"
    "sauce-mousseuse"
    "sauce-moutarde"
    "sauce-nantua"
    "sauce-new-burg-avec-le-homard-cru"
    "nota-sauce-new-burg-avec-le-homard-cru"
    "sauce-new-burg-avec-le-homard-cuit"
    "nota-sauce-new-burg-b"
    "sauce-noisette"
    "sauce-normande"
    "nota-sauce-normande"
    "sauce-orientale"
    "sauce-paloise"
    "sauce-poulette"
    "sauce-ravigote"
    "sauce-regence-pour-poissons"
    "sauce-regence-pour-garnitures-de-volaille"
    "sauce-riche"
    "sauce-rubens"
    "sauce-saint-malo"
    "sauce-smitane"
    "sauce-solferino"
    "nota-sauce-solferino"
    "sauce-soubise"
    "nota-sauce-soubise"
    "sauce-soubise-tomatee"
    "sauce-souchet"
    "sauce-tyrolienne"
    "sauce-tyrolienne-a-l-ancienne"
    "sauce-valois"
    "nota-sauce-valois"
    "sauce-venitienne"
    "sauce-veron"
    "sauce-villageoise"
    "sauce-villeroy"
    "nota-sauce-villeroy"
    "sauce-villeroy-soubisee"
    "sauce-villeroy-tomatee"
    "sauce-vin-blanc")
   (LaTeX-add-index-entries
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!あるひゆふえら@---・アルビュフェラ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!albufera@--- Albuféra"
    "そーす@ソース!あるひゆふえら@---・アルビュフェラ"
    "あるひゆふえら@アルビュフェラ!そーす@ソース・---"
    "sauce@sauce!albufera@--- Albuféra"
    "albufera@Albuféra!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!あめりけーぬ@---・アメリケーヌ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!americaine@--- Américaine"
    "そーす@ソース!あめりけーぬ@---・アメリケーヌ"
    "あめりかん@アメリカン/アメリケーヌ!そーす@ソース・アメリケーヌ"
    "sauce@sauce!americaine@--- américaine"
    "americain@américain(e)!sauce americaine@sauce ---e"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!あんちよひ@アンチョビ---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!anchois@--- Anchois"
    "そーす@ソース!あんちよひ@アンチョビ---"
    "あんちよひ@アンチョビ!そーす@---ソース"
    "sauce@sauce!anchois@--- Anchois"
    "anchois@anchois!sauce anchois@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!おーろーる@---・オーロール"
    "そーす@ソース!おーろーる@---・オーロール"
    "おーろーる@オーロール!そーす@ソース・---"
    "sauce@sauce!aurore@--- Aurore"
    "aurore@aurore!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!おーろーるさかなよう@魚料理用---・オーロール"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!aurore maigre@--- Aurore maigre"
    "そーす@ソース!おーろーるさかなよう@魚料理用---・オーロール"
    "おーろーる@オーロール!そーすさかな@魚料理用ソース・---"
    "sauce@sauce!aurore maigre@--- Aurore maigre"
    "aurore@aurore!sauce maigre@Sauce --- maigre"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!はいえるんふう@バイエルン風---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!bavaroise@--- Bavaroise"
    "そーす@ソース!はいえるんふう@バイエルン風---"
    "はいえるんふう@バイエルン風!そーす@---ソース"
    "sauce@sauce!bavaroise@--- Bavaroise"
    "bavarois@bavarois(e)!sauce bavaroise@Sauce ---(e)"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!へあるねーす@---・ベアルネーズ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!bearnaise@--- Béarnaise"
    "そーす@ソース!へあるねーす@---・ベアルネーズ"
    "へあるぬふう@ベアルヌ風!そーす@ソース・---"
    "へあるねーす@ベアルネーズ!そーす@ソース・---"
    "sauce@sauce!bearnaise@--- Béarnaise"
    "bearnais@béarnais(e)!sauce bearnaise@Sauce ---e"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!へあるねーすとまといり@トマト入り---・ベアルネーズ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!bearnaise tomatee@--- Béarnaise tomatée"
    "そーす@ソース!へあるねーすとまといり@トマト入り---・ベアルネーズ"
    "へあるぬふう@ベアルヌ風!そーすとまといり@トマト入りソース・ベアルネーズ"
    "そーす@ソース!しよろん@---・ショロン"
    "しよろん@ショロン!そーす@ソース・---"
    "sauce@sauce!bearnaise tomatee@--- Béarnaise tomatée"
    "bearnais@b\\'earnais!sauce bearnaise tomatee@Sauce Béarnaise tomatée"
    "sauce@sauce!choron@--- Choron"
    "choron@Choron!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!へあるねーすくらすとういあんといり@グラスドヴィアント入り---・ベアルネーズ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!bearnaise glace viande@--- à la glace de viande"
    "へあるぬふう@ベアルヌ風!そーすくらすとういあんといり@グラスドヴィアンド入りソース・ベアルネーズ"
    "そーす@ソース!へあるねーすくらすとういあんといり@---・ベアルネーズ(グラス・ド・ヴィアンド入り)"
    "そーす@ソース!ふおいよ@---・フォイヨ"
    "ふおいよ@フォイヨ!そーす@ソース・---"
    "そーす@ソース!うあろわ@---・ヴァロワ"
    "うあろわ@ヴァロワ!そーす@ソース・---"
    "sauce@sauce!bearnaise a la glace de viande@--- Béarnaise à la glace de viande"
    "bearnais@b\\'earnais!sauce bearnaise a la glace de viande@Sauce Béarnaise à la glace de viande"
    "sauce@sauce!foyot@--- Foyot"
    "foyot@Foyot!sauce@Sauce ---"
    "sauce@sauce!valois@--- Valois"
    "valois@Valois!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!へるしー@---・ベルシー"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!bercy@--- Bercy"
    "そーす@ソース!へるしー@---・ベルシー"
    "へるしー@ベルシー!そーす@ソース・---"
    "sauce@sauce!bercy@--- Bercy"
    "bercy@Bercy!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!ふーる@---・オ・ブール"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!beurre@--- au Beurre"
    "そーす@ソース!ふーる@---・オ・ブール"
    "はたー@バター!そーす@ソース・オ・ブール"
    "そーす@ソース!はたると@---・バタルド"
    "はたると@バタルド!そーす@ソース・---"
    "sauce@sauce!beurre@--- au Beurre"
    "beurre@beurre!sauce@Sauce au Beurre"
    "sauce@sauce!batarde@--- Bâtarde"
    "batard@bâtard!sauce@Sauce Bâtarde"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!ほぬふおわ@---・ボヌフォワ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!bonnegoy@--- Bonnefoy"
    "ほぬふおわ@ボヌフォワ!そーす@ソース・---"
    "そーす@ソース!ほぬふおわ@---・ボヌフォワ"
    "そーす@ソース!ほるとーふうしろわいん@ボルドー風--- (白)"
    "ほるとーふう@ボルドー風!そーすしろ@---ソース(白)"
    "sauce@sauce!bonnefoy@--- Bonnefoy"
    "bonnefoy@Bonnefoy!sauce@Sauce ---"
    "sauce@sauce!bordelaise vin blanc@--- Bordelaise au vin blanc"
    "bordelais@bordelais!sauce vin blanc@Sauce Bordelaise au vin blanc"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!ふるたーにゆ@ブルターニュ風---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!bretonne@--- Bretonne"
    "そーす@ソース!ふるたーにゆふうしろ@ブルターニュ風---（ホワイト系）"
    "ふるたーにゆふう@ブルターニュ風!そーすしろ@---ソース（ホワイト系）"
    "sauce@sauce!bretonne blanche@--- Bretonne (blanche)"
    "breton@breton!sauce blanche@Sauce Bretonne (blanche)"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!かのていえーる@---・カノティエール"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!canotiere@--- Canotière"
    "そーす@ソース!かのていえーる@---・カノティエール"
    "かのていえーる@カノティエール!そーす@ソース・---"
    "sauce@sauce!canotiere@--- Canotière"
    "canotier@canotier(ère)!sauce@Sauce Canotière"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!けいはー@ケイパー入り---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!capres@--- qux Câpres"
    "そーす@ソース!けいはー@ケイパー入り---"
    "けいはー@ケイパー!そーす@---入りソース"
    "sauce@sauce!capres@--- aux Câpres"
    "capre@câpre!sauce capres@Sauce aux Câpres"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!かるていなる@---・カルディナル"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!cardinal@--- Cardinal"
    "そーす@ソース!かるていなる@---・カルディナル"
    "かるていなる@カルディナル!そーす@ソース・---"
    "sauce@sauce!cardinal@--- Cardinal"
    "cardinal@cardinal!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!まつしゆるーむ@マッシュルーム入り---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!champignons@--- aux Champignons"
    "そーす@ソース!まつしゆるーむしろ@マッシュルーム---（ホワイト系）"
    "まつしゆるーむ@マッシュルーム!そーすしろ@---ソース（ホワイト系）"
    "sauce@sauce!champignonsblanche@--- aux Champignons (blanches)"
    "champignon@champignon!sauce blanche@Sauce aux Champignons (blanche)"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!しやんていい@---・シャンティイ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!chantillys@--- Chantilly"
    "そーす@ソース!しやんていい@---・シャンティイ"
    "しやんていい@シャンティイ!そーす@ソース・---"
    "sauce@sauce!chantilly@--- Chantilly"
    "chantilly@Chantilly!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!しやとーふりやん@---・シャトーブリヤン"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!chateaubriand@--- Chateaubriand"
    "そーす@ソース!しゃとーふりやん@---・シャトーブリヤン"
    "しゃとーふりやん@シャトーブリヤン! そーす@ソース・---"
    "sauce@sauce!chateaubriand@--- Chateaubriand"
    "chateaubriand@Chateaubriand!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!しよふろわしろ@白い---・ショフロワ（標準）"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!chaud-froid blanche ordinaire@--- Chaud-froid blanche ordinaire"
    "そーす@ソース!しよふろわしろ@白い---・ショフロワ（標準）"
    "しよふろわ@ショフロワ!そーすしろ@白いソース---（標準）"
    "sauce@sauce!chaud-froid blanche ordinaire@--- Chaud-froid blanche ordinaire"
    "chaud-froid@chaud-froid!sauce blanche ordinaire@Sauce --- blanche ordinaire"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!しよふろわふろんと@ブロンドの---・ショフロワ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!chaud-froid blonde@--- Chaud-froid blonde"
    "そーす@ソース!しよふろわふろんと@ブロンドの---・ショーフロワ"
    "しよふろわ@ショーフロワ!そーすふろんと@ブロンドのソース---"
    "sauce@sauce!chaud-froid blonde@--- Chaud-froid blonde"
    "chaud-froid@chaud-froid!sauce blonde@Sauce --- blonde"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!しよふろわおーろーる@---・ショフロワ・オーロール"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!chaud-froid aurore@--- Chaud-froid Aurore"
    "そーす@ソース!しよふろわおーろーる@---・ショーフロワ・オーロール"
    "しよふろわ@ショーフロワ!そーすおーろーる@ソース・---・オーロール"
    "おーろーる@オーロール!そーすしよふろわおーろーる@ソース・ショーフロワ・---"
    "sauce@sauce!chaud-froid aurore@--- Chaud-froid Aurore"
    "chaud-froid@chaud-froid!sauce aurore@Sauce --- Aurore"
    "aurore@aurore!sauce chaud-froid aurore@Sauce Chaud-froid ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!しよふろわうえーるふれ@---・ショフロワ・ヴェールプレ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!chaud-froid vert-pre@--- Chaud-froid au Vert-pré"
    "そーす@ソース!しよふろわうえーるふれ@---・ショーフロワ・ヴェールプレ"
    "しよふろわ@ショーフロワ!そーすうえーるふれ@ソース・---・ヴェールプレ"
    "うえーるふれ@ヴェールプレ!そーすしよふろわうえーるふれ@ソース・ショーフロワ・---"
    "sauce@sauce!chaud-froid vert-pre@--- Chaud-froid au Vert-pré"
    "chaud-froid@chaud-froid!sauce vert-pre@Sauce --- au Vert-pré"
    "vert-pre@vert-pré!sauce chaud-froid vert-pre@Sauce Chaud-froid au ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!しよふろわさかなりようりよう@魚料理用---・ショフロワ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!chaud-froid maigre@--- Chaud-froid maigre"
    "そーす@ソース!さかなりようりようしよふろわ@魚料理用---・ショフロワ"
    "しよふろわ@ショフロワ!さかなりようりようそーす@魚料理用ソース---"
    "sauce@sauce!chaud-froid maigre@--- Chaud-froid maigre"
    "chaud-froid@chaud-froid!sauce maigre@Sauce --- maigre"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!しうり@---・シヴリ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!chivry@--- Chivry"
    "そーす@ソース!しうり@---・シヴリ"
    "しうり@シヴリ!そーす@ソース・---"
    "sauce@sauce!chivry@--- Chivry"
    "chivry@Chivry!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!くれーむ@---・クレーム"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!creme@--- à la Crème"
    "そーす@ソース!くれーむ@---・クレーム"
    "くりーむ@クリーム!そーす@ソース・クレーム"
    "sauce@sauce!creme@--- à la Crème"
    "creme@crème!sauce@Sauce à la ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!くるうえつと@---・クルヴェット"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!crevettes@--- aux Crevettes"
    "そーす@ソース!くるうえつと@---・クルヴェット"
    "くるうえつと@クルヴェット!そーす@ソース・---"
    "sauce@sauce!crevette@--- aux Crevettes"
    "crevette@crevette!sauce@Sauce aux Crevettes"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!かれー@カレー---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!currie@--- Currie"
    "そーす@ソース!かれー@カレー---"
    "かれー@カレー!そーす@---ソース"
    "sauce@sauce!currie@---  Currie"
    "currie@currie!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!いんとふうかれー@インド風カレー---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!currie indienne@--- Currie à l'Indienne"
    "そーす@ソース!いんとふうかれー@インドカレー---"
    "かれー@カレー!そーすいんとふう@インド---ソース"
    "sauce@sauce!currie indienne@---  Currie à l'Indienne"
    "currie@currie!sauce indienne@Sauce --- à l'Indienne"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!ていふろまつと@---・ディプロマット"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!diplomate@--- Diplomate"
    "そーす@ソース!ていふろまつと@---・ディプロマット"
    "ていふろまつと@ディプロマット!そーす@ソース・---"
    "sauce@sauce!diplomate@--- Diplomate"
    "diplomat@diplomat(e)!sauce@Sauce ---e "
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!すこつとらんとふう@スコットランド風---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!ecossaise@--- Ecossaise"
    "そーす@ソース!すこつとらんとふう@スコットランド風---"
    "すこつとらんとふう@スコットランド風!そーす@---ソース"
    "sauce@sauce!ecossaise@--- Ecossaise"
    "ecossais@écossais(e)!sauce@Sauce ---e"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!えすとらこん@---・エストラゴン"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!estragon@--- Estragon"
    "そーす@ソース!えすとらこんしろ@---・エストラゴン（ホワイト系）"
    "えすとらこん@エストラゴン!そーす@ソース・--- （ホワイト系）"
    "sauce@sauce!estragon blanche@--- Estragon (blanche)"
    "estragon@estragon!sauce blanche@Sauce --- (blanche)"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!こうそう@香草---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!fines herbes@--- aux Fines Herbes"
    "そーす@ソース!こうそうしろ@香草---（ホワイト系）"
    "こうそう@香草!そーすしろ@---ソース（ホワイト系）"
    "はーぶ@ハーブ ⇒ 香草!こうそうそーすしろ@香草ソース（ホワイト系）"
    "sauce@sauce!fines herbes blanche@--- aux Fines Herbes (blanche)"
    "fines herbes@fines herbes!sauce blanche@Sauce aux --- (blanche)"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!くろせいゆ@---・グロセイユ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!groseilles@--- Groseilles"
    "そーす@ソース!くろせいゆ@---・グロゼイユ"
    "くろせいゆ@グロゼイユ!そーす@ソース・---"
    "sauce@sauce!groseilles@--- Groseilles"
    "groseille@groseille!sauce@Sauce ---s"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!おらんてーす@オランデーズ---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!hollandaise@--- Hollandaise"
    "そーす@ソース!おらんてーす@オランデーズ---"
    "おらんてーす@オランデーズ!そーす@---ソース"
    "おらんたふう@オランダ風!そーす@オランデーズソース"
    "sauce@sauce!hollandaise@--- Hollandaise"
    "hollandais@hollandais(e)!sauce@Sauce ---e"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!おまーる@---・オマール"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!homard@--- HOmard"
    "そーす@ソース!おまーる@---・オマール"
    "おまーる@オマール!そーす@ソース・---"
    "sauce@sauce!homard@--- Homard"
    "homard@homard!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!はんかりーふう@ハンガリー風---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!hongroise@--- Hongroise"
    "そーす@ソース!はんかりーふう@ハンガリー風---"
    "はんかりーふう@ハンガリー風!そーす@---ソース"
    "sauce@sauce!hongroise@---  Hongroise"
    "hongrois@hongrois(e)!sauce@Sauce ---e"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!かきいり@牡蠣入り---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!huitres@--- aux Huîtres"
    "そーす@ソース!かきいり@牡蠣入り---"
    "かき@牡蠣!そーす@牡蠣入りソース"
    "sauce@sauce!huitres@---  aux Huîtres"
    "huitre@huître!sauce@Sauce aux Huîtres"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!いんとふう@インド風---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!indienne@--- Indienne"
    "そーす@ソース!いんとふう@インド風---"
    "いんとふう@インド風!そーす@---ソース"
    "sauce@sauce!indienne@---  Indienne"
    "indien@indien(ne)!sauce@Sauce ---ne"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!いうおあーる@---・イヴォワール"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!ivoire@--- Ivoire"
    "そーす@ソース!いうおわーる@---・イヴォワール"
    "いうおわーる@イヴォワール!そーす@ソース・---"
    "sauce@sauce!ivoire@--- Ivoire"
    "ivoire@ivoire!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!しよわんういる@---・ジョワンヴィル"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!joinville@--- Joinville"
    "しよわんういる@ジョワンヴィル!そーす@ソース・---"
    "そーす@ソース!しよわんういる@---・ジョワンヴィル"
    "sauce@sauce!joinville@--- Joinville"
    "joinville@Joinville!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!らきひえーる@---・ラギピエール"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!laguipiere@--- Laguipière"
    "らきひえーる@ラギピエール!そーす@ソース・---"
    "そーす@ソース!らきひえーる@---・ラギピエール"
    "sauce@sauce!laguipiere@--- Laguipière"
    "laguipiere@Laguipière!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!りうおにあふう@リヴォニア風---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!livoinienne@--- Livoinienne"
    "そーす@ソース!りうおにあふう@リヴォニア風---"
    "りうおにあふう@リヴォニア風!そーす@---ソース"
    "sauce@sauce!livonienne@---  Livonienne"
    "livonien@livonien(ne)!sauce@Sauce ---ne"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!まるたふう@マルタ風---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!maltaise@--- Maltaise"
    "そーす@ソース!まるたふう@マルタ風---"
    "まるたふう@マルタ風!そーす@---ソース"
    "maltais@maltais(e)!sauce@Sauce ---e"
    "sauce@sauce!maltaise@--- Maltaise"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!まりにえーる@---・マリニエール"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!mariniere@--- Marinière"
    "まりにえーる@マリニエール!そーす@ソース・---"
    "そーす@ソース!まりにえーる@---・マリニエール"
    "sauce@sauce!mariniere@--- Marinière"
    "marinier@marinier(ère)!sauce@Sauce Marinière"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!まとろっと@---・マトロット"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!matelote@--- Matelote blanche"
    "そーす@ソース!まとろつとしろ@白い---・マトロット"
    "まとろつと@マトロット!そーすしろ@白いソース・---"
    "sauce@sauce!matelote blanche@--- Matelote blanche"
    "matelote@matelote!sauce@Sauce --- blanche"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!もるねー@---・モルネー"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!mornay@--- Mornay"
    "もるねー@モルネー!そーす@---ソース"
    "そーす@ソース!もるねー@---・モルネー"
    "sauce@sauce!mornay@--- Mornay"
    "mornay@Mornay!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!むすりーぬ@---・ムスリーヌ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!mousseline@--- Mousseline"
    "むすりーぬ@ムスリーヌ!そーす@ソース・---"
    "そーす@ソース!むすりーぬ@---・ムスリーヌ"
    "sauce@sauce!mousseine@--- Mousseline"
    "mousseline@mousseline!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!むすーす@---・ムスーズ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!mousseuse@--- Mousseuse"
    "むすー@ムスー（ズ）!そーす@ソース・ムスーズ"
    "そーす@ソース!むすーす@---・ムスーズ"
    "sauce@sauce!mousseuse@--- Mousseuse"
    "mousseux@mousseux/mousseuse!sauce@Sauce Mousseuse"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!むたると@---・ムタルド"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!moutarde@--- Moutarde"
    "そーす@ソース!むたると@---・ムタルド"
    "むたると@ムタルド（マスタード）!そーす@ソース・ムタルド"
    "ますたーと@マスタード（ムタルド）!そーす@ソース・ムタルド"
    "sauce@sauce!moutarde@--- Moutarde"
    "moutarde@moutarde!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!なんちゆあ@---・ナンチュア"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!nantua@--- Nantua"
    "そーす@ソース!なんちゆあ@---・ナンチュア"
    "なんちゆあ@ナンチュア!そーす@ソース・---"
    "えくるういす@エクルヴィス!そーす@ソース・ナンチュア"
    "sauce@sauce!nantua@--- Nantua"
    "nantua@Nantua!sauce@Sauce ---"
    "ecrevisse@ecrevisse!sauce@Sauce Nantua"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!にゆーはーくいけおまーる@活けオマールで作る---・ニューバーグ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!new-burg homard cru@--- New-burg avec le homard cru"
    "そーす@ソース!にゆーはーくいけおまーる@活けオマールを使う---・ニューバーグ"
    "にゆーはーく@ニューバーグ!そーすいけおまーる@活けオマールを使うソース・---"
    "sauce@sauce!new-burg homard cru@--- New-burg avec le homard cru"
    "new-burg@New-burg!sauce homard cru@Sauce --- avec le homard cru"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!にゆーはーくゆてたおまーる@茹でたオマールで作る---・ニューバーグ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!new-burg homard cru@--- New-burg avec le homard cuit"
    "そーす@ソース!にゆーはーくゆてたおまーる@茹でたオマールを使う---・ニューバーグ"
    "にゆーはーく@ニューバーグ!そーすゆてたおまーる@茹でたオマールを使うソース・---"
    "sauce@sauce!new-burg homard cuit@--- New-burg avec le homard cuit"
    "new-burg@New-burg!sauce homard cuit@Sauce --- avec le homard cuit"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!のわせつと@---・ノワゼット"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!noisette@--- NOisette"
    "そーす@ソース!へーせるなっつ@---・ノワゼット"
    "へーせるなつつ@ヘーゼルナッツ!そーす@ソース・ノワゼット"
    "のわせつと@ノワゼット!へーぜるなっつそーす@ヘーゼルナッツソース"
    "sauce@sauce!noisette@--- Noisette"
    "noisette@noisette!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!のるまんていふう@ノルマンディ風---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!normande@--- NOrmande"
    "そーす@ソース!のるまんてふう@ノルマンディ風---"
    "のるまんていふう@ノルマンディ風!そーす@---ソース"
    "sauce@sauce!normande@--- Normande"
    "normande@normande!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!おりえんとふう@オリエント風---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!orientale@--- Orientale"
    "そーす@ソース!おりえんとふう@オリエント風---"
    "おりえんとふう@オリエント風!そーす@---ソース"
    "とうほうふう@東方風!おりえんたるそーす@オリエント風ソース"
    "sauce@sauce!orientale@--- Orientale"
    "oriental@oriental(e)!sauce@Sauce ---e"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!ほーふう@ポー風---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!paloise@--- paloise"
    "そーす@ソース!ほーふう@ポー風---"
    "ほーふう@ポー風!そーす@---ソース"
    "sauce@sauce!paloise@--- Paloise"
    "palois@palois!sauce@Sauce Paloise"
    "pau@Pau!sauce paloise@Sauce Paloise"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!ふれつと@---・プレット"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!poulette@--- Poulette"
    "そーす@ソース!ふれつと@---・プレット"
    "ふれつと@プレット!そーす@ソース・---"
    "sauce@sauce!poulette@--- Poulette"
    "poulette@poulette!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!らういこつと@---・ラヴィゴット"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!ravigote@--- Ravigote"
    "そーす@ソース!らういこつと@---・ラヴィゴット"
    "らういこつと@ラヴィゴット!そーす@ソース・---"
    "sauce@sauce!ravigote@--- Ravigote"
    "ravigote@ravigote!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!れしやんすさかなよう@魚料理用---・レジャンス"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!regence pour poisson@--- Régence pour Poissons"
    "そーす@ソース!れしやんすさかなよう@魚料理用---・レジャンス"
    "れしやんす@レジャンス!そーすさかなよう@魚料理用ソース・---"
    "sauce@sauce!regence poissons@--- Régence pour Poissons"
    "regence@Régence!sauce poissons@Sauce --- pour Poissons"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!れしやんすとりりようりよう@鶏料理のガルニチュール用---・レジャンス"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!regence pour garnitures de volaille@--- Régence pour garnitures de Volaille"
    "そーす@ソース!れしやんすとりりようりのかるにてゆーるよう@鶏料理のガルニチュール用---・レジャンス"
    "れしやんす@レジャンス!そーすとりりようりののかるにてゅーるよう@鶏料理のガルニチュール用ソース・---"
    "sauce@sauce!regence garnitures de volaille@--- Régence pour garnitures de Volaille"
    "regence@Régence!sauce garnitures de volaille@Sauce --- pour garnitures de Volaille"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!りつしゆ@---・リッシュ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!riche@--- Riche"
    "そーす@ソース!りつしゆ@---・リッシュ"
    "りつしゆ@リッシュ!そーす@ソース・---"
    "sauce@sauce!riche@--- Riche"
    "riche@riche!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!るーへんす@---・ルーベンス"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!rubens@--- Rubens"
    "そーす@ソース!るーへんす@---・ルーベンス"
    "るーへんす@ルーベンス!そーす@ソース・---"
    "rubens@Rubens!sauce@Sauce ---"
    "sauce@sauce!rubens@--- Rubens"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!さんまろふう@サンマロ風---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!saint-malo@--- Saint-Malo"
    "そーす@ソース!さんまろふう@サンマロ風---"
    "さんまろふう@サンマロ風!そーす@---ソース"
    "sauce@sauce!saint-malo@--- Saint-Malo"
    "saint-malo@Saint-Malo!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!すみたーぬ@---・スミターヌ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!smitane@--- Smitane"
    "すみたーぬ@スミターヌ!そーす@ソース・---"
    "そーす@ソース!すみたーぬ@---・スミターヌ"
    "さわーくりーむ@サワークリーム!そーすすみたーぬ@ソース・スミターヌ"
    "sauce@sauce!smitane@--- Smitane"
    "smitane@smitane!sauce@Sauce ---"
    "creme aigre@crème aigre!sauce smitane@Sauce Smitane"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!そるふえりの@---・ソルフェリノ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!rubens@--- Solférino"
    "そーす@ソース!そるふえりの@---・ソルフェリノ"
    "そるふえりの@ソルフェリノ!そーす@ソース・---"
    "sauce@sauce!solferino@--- Solférino"
    "solferino@Solférino!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!すひーす@---・スビーズ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!soubise@--- Soubise"
    "そーす@ソース!すひーす@---・スビーズ"
    "すひーす@スビーズ!そーす@ソース・---"
    "くり@クリ!たまねぎのくりすひーず@玉ねぎのクリ・スビーズ"
    "sauce@sauce!soubise@--- Soubise"
    "soubise@Soubise!sauce@Sauce ---"
    "coulis@coulis!oignons soubise@Coulis d'oignons Soubise"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!すひーすとまといり@トマト入り---・スビース"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!soubise tomatee@--- Soubise tomatée"
    "そーす@ソース!すひーすとまといり@トマト入り---・スゥビーズ"
    "すひーす@スビーズ!そーすとまといり@トマト入りソース・---"
    "sauce@sauce!soubise tomatee@--- Soubise tomatée"
    "soubise@Soubise!sauce tomatee@Sauce --- tomatée"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!すーしえ@---・スーシェ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!souchet@--- Souchet"
    "そーす@ソース!すーしえ@---・スーシェ"
    "すーしえ@スーシェ!そーす@ソース・---"
    "sauce@sauce!souchet@--- Souchet"
    "souchet@Souchet!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!ちろるふう@チロル風---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!tyrolienne@--- Tyrolienne"
    "そーす@ソース!ちろるふう@チロル風---"
    "ちろるふう@チロル風!そーす@---ソース"
    "sauce@sauce!tyrolienne@--- Tyrolienne"
    "tyrolien@tyrolien(ne)!sauce@Sauce ---ne"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!ちろるふうくらしつく@チロル風---　クラシック"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!tyrolienne ancienne@--- Tyrolienne à l'ancienne"
    "そーす@ソース!ちろるふうくらしつく@チロル風---　クラシック"
    "ちろるふう@チロル風!そーす@---ソース　クラシック"
    "sauce@sauce!tyrolienne ancienne@--- Tyrolienne à l'ancienne"
    "tyrolien@Tyrolien!sauce ancienne@Sauce Tyrolienne à l'ancienne"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!うわろわ@---・ヴァロワ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!valois@--- Valois"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!うえねついあふう@ヴェネツィア風---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!venitienne@--- Vénitienne"
    "そーす@ソース!うえねついあふう@ヴェネツィア風---"
    "うえねついあふう@ヴェネツィア風!そーす@---ソース"
    "sauce@sauce!venitienne@--- Vénitienne"
    "venitien@vénitien(ne)!sauce@Sauce ---ne"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!うえろん@---・ヴェロン"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!veron@--- Véron"
    "そーす@ソース!うえろん@---・ヴェロン"
    "うえろん@ヴェロン!そーす@ソース・---"
    "veron@Véron!sauce@Sauce ---"
    "sauce@sauce!veron@--- Véron"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!むらひとふう@村人風---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!villageoise@--- Villageoise"
    "そーす@ソース!むらひとふう@村人風---"
    "むらひとふう@村人風!そーす@---ソース"
    "sauce@sauce!villageoise@--- Villageoise"
    "villageois@villageois!sauce@Sauce Villageoise"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!ういるろわ@---・ヴィルロワ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!villeroy@--- Villeroy"
    "そーす@ソース!ういるろわ@---・ヴィルロワ"
    "ういるろわ@ヴィルロワ!そーす@ソース・---"
    "sauce@sauce!villeroy@--- Villeroy"
    "villeroy@Villeroy!sauce@Sauce ---"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!ういるろわすひーすいり@スビーズ入り---・ヴィルロワ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!villeroy soubisee@--- Villeroy Soubisée"
    "そーす@ソース!ういるろわすひーすいり@スビーズ入り---・ヴィルロワ"
    "ういるろわ@ヴィルロワ!そーすすひーすいり@スビーズ入りソース・---"
    "sauce@sauce!villeroy soubisee@--- Villeroy Soubisée"
    "villeroy@Villeroy!sauce soubisee@Sauce --- Soubisée"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!ういるろわとまといり@トマト入り---・ヴィルロワ"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!villeroy tomatee@--- Villeroy tomatée"
    "そーす@ソース!ういるろわとまといり@トマト入り---・ヴィルロワ"
    "ういるろわ@ヴィルロワ!そーすとまといり@トマト入りソース・---"
    "sauce@sauce!villeroy tomatee@--- Villeroy tomatée"
    "villeroy@Villeroy!sauce tomatee@Sauce --- tomatée"
    "そーす@ソース!ほわいとはせい@ホワイト系の派生---!しろわいん@白ワイン---"
    "sauce@sauce!petites blanches composees@Petites ---s Blanches Composées!vin blanc@--- Vin blanc"
    "そーす@ソース!しろわいん@白ワイン---"
    "しろわいん@白ワイン!そーす@---ソース"
    "わいん@ワイン!しろわいん@白ワイン!そーす@---ソース"
    "sauce@sauce!vin blanc@--- vin blanc"
    "vin@vin!sauce vin blanc@Sauce vin blanc"))
 :latex)

