(TeX-add-style-hook
 "echantillon-01"
 (lambda ()
   (LaTeX-add-labels
    "ux30a8ux30b9ux30b3ux30d5ux30a3ux30a8ux306eux65b0ux89e3ux91c8-ux53c2ux8003ux4f8b"
    "les-hors-d-oeuvres"
    "bouchees"
    "bouchee-a-la-reine"
    "epinards-a-la-viroflay"
    "subric-d-epinards"
    "nota-subric-d-epinards"
    "Potages"
    "consomme-rabelais"
    "puree-conde"
    "puree-conti"
    "les-poissons"
    "sole-duglere"
    "coulibiac-de-saumon-a"
    "note-sur-vesiga"
    "ux8089ux6599ux7406"
    "boeuf-a-la-mode"
    "haricot-de-mouton"
    "poularde-albufera"
    "ux30c7ux30b6ux30fcux30c8"
    "cerises-jubilee"
    "timbale-d-arenberg"
    "sauce-a-l-abricot")
   (LaTeX-add-index-entries
    "sole@sole!duglere@--- Dugléré"
    "duglere@Dugléré!sole@sole ---"
    "したひらめ@舌びらめ!てゆくれれ@--- ・デュグレレ"
    "てゆくれれ@デュグレレ!したひらめ@舌びらめ・---"
    "そーる@ソール ⇒ 舌びらめ!てゆくれれ@---・デュグレレ"
    "saumon@saumon!coulibiac a@Coulibiac de --- A"
    "coulibiac@coulibiac!saumon a@--- de Saumon A"
    "さけ@鮭 ⇒ サーモン"
    "さーもん@サーモン!くりひやつくa!サーモンのクリビヤックA"
    "くりひやつく@クリビヤック!さーもんa!サーモンの--- A"
    "boeuf@boeuf!mode@--- à la mode"
    "piece de boeuf@pièce de boeuf!mode@Boeuf à la mode"
    "mode@mode (à la)!boeuf@Boeuf à la mode"
    "うしかたまりにく@牛塊肉!もーと@ブフアラモード"
    "ふふ@ブフ!もーと@ブルアラモード"
    "もーと@モード!ふふあらもーと@ブフアラモード"
    "あらもーと@アラモード!ふふ@ブフ---"
    "haricot@haricot!mouton@--- de mouton"
    "mouton@mouton!haricot@Haricot de ---"
    "ありこ@アリコ!ひつし@羊の---"
    "ひつし@羊!ありこ@---のアリコ"
    "poularde@poularde!albufera@Albuféra"
    "albufera@Albuféra!poularde@Poularde ---"
    "ひとり@肥鶏!あるひゆふえら@---・アルビュフェラ"
    "ふーらると@プーラルド ⇒ 肥鶏!あるひゆふえら@---・アルビュフェラ"
    "あるひゆふえら@アルビュフェラ!ひとり@肥鶏・---"))
 :latex)

