(TeX-add-style-hook
 "02-04-pp89-103"
 (lambda ()
   (LaTeX-add-labels
    "garnitures-recettes"
    "garniture-algerienne"
    "garniture-alsacienne"
    "garniture-americaine"
    "garniture-andalouse"
    "garniture-arlesienne"
    "garniture-banquiere"
    "garniture-berrichonne"
    "garniture-berny"
    "garniture-bezontinne"
    "garniture-boulangere"
    "garniture-bouquetiere"
    "garniture-bourgeoise"
    "garniture-brabanconne"
    "garniture-brehan"
    "garniture-bretonne"
    "garniture-brillat-savarin"
    "garniture-bristol"
    "garniture-bluxelloise"
    "garniture-cancalaise"
    "garniture-cardinal"
    "garniture-castillane"
    "garniture-chambord"
    "garniture-chatelaine"
    "garniture-chipolata"
    "garniture-choisy"
    "garniture-choron"
    "garniture-clamart"
    "garniture-de-compote"
    "garniture-conti"
    "garniture-a-la-commodore"
    "garniture-cussy"
    "garniture-Daumont"
    "garniture-a-la-dauphine"
    "garniture-a-la-dieppoise"
    "garniture-doria"
    "garniture-dubarry"
    "garniture-a-la-duchesse"
    "garniture-a-la-favorite"
    "garniture-a-la-fermiere"
    "garniture-a-la-financiere"
    "garniture-a-la-flamande"
    "garniture-a-la-florentine"
    "garniture-Florian"
    "garniture-a-la-Forestiere"
    "garniture-frascati"
    "garniture-a-la-gastronome"
    "garniture-godard"
    "garniture-grand-duc"
    "garniture-a-la-grecque"
    "garniture-henri-iv"
    "garniture-a-la-hongroise"
    "garniture-a-l-italienne"
    "garniture-a-l-indienne"
    "garniture-a-la-japonaise"
    "garniture-a-la-jardiniere"
    "garniture-joinville"
    "garniture-judic"
    "garniture-languedocienne"
    "garniture-lorette"
    "garniture-louisiane"
    "garniture-lucullus"
    "garniture-macedoine"
    "garniture-madeleine"
    "garniture-a-la-maillot"
    "garniture-a-la-maraichere"
    "garniture-marechal"
    "a."
    "b."
    "garniture-marie-louise"
    "garniture-marniere"
    "garniture-marquise"
    "garniture-a-la-marseillaise"
    "garniture-mascotte"
    "nota-garniture-mascotte"
    "garniture-massena"
    "garniture-matelote"
    "garniture-medicis"
    "garniture-a-la-mexicaine"
    "garniture-mignon"
    "garniture-a-la-milanaise"
    "garniture-mirabeau"
    "garniture-mirette"
    "garniture-a-la-moderne"
    "garniture-montbazon")
   (LaTeX-add-index-entries
    "garniture@garniture!algerienne@--- à l'Algérienne"
    "algerien@algérien(nne)!garuniture à l'---ne"
    "かるにちゆーる@ガルニチュール!あるしえりあふう@---・アルジェリア風"
    "あるしえりあふう@アルジェリア風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!alsacienne@--- à l'Alsacienne"
    "alsacien@alsacien(ne)!garuniture à l'---ne"
    "かるにちゆーる@ガルニチュール!あるさすふう@---・アルザス風"
    "あるさすふう@アルザス風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!americaine@--- à l'Américaine"
    "americain@américain(e)!garuniture à l'---e"
    "かるにちゆーる@ガルニチュール!あめりけーぬ@---・アメリケーヌ"
    "あめりかん@アメリカン/アメリケーヌ!かるにちゆーる@ガルニチュール・アメリケーヌ"
    "garniture@garniture!andalouse@--- à l'Andalouse"
    "andalou@andalou(se)!garuniture à l'---se"
    "かるにちゆーる@ガルニチュール!あんたるしあふう@---・アンダルシア風"
    "あんたるしあふう@アンダルシア風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!arlesienne@--- à l'Arlésienne"
    "arlesien@arlésien(ne)!garuniture à l'---ne"
    "かるにちゆーる@ガルニチュール!あるるふう@---・アルル風"
    "あるるふう@アルル風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!banauiere@--- à la Banquière"
    "banquier@banquier(ère)!garuniture à la Banquière"
    "かるにちゆーる@ガルニチュール!きんこうかふしんふう@---・銀行家夫人風"
    "きんこうかふしんふう@銀行家夫人風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!berrichonne@--- à la Berrichonne"
    "berrichon@berrichon(ne)!garuniture à la Berrichonne"
    "かるにちゆーる@ガルニチュール!へりーふう@---・ベリー風"
    "へりーふう@ベリー風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!berny@--- à la Berny"
    "Berny@Berny (Bernis)!garuniture à la Berny"
    "かるにちゆーる@ガルニチュール!へるに@---・ベルニ"
    "へるに@ベルニ!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!bizontinne@--- à la Bizontine"
    "bizontin@bizontin(e) ⇒ bisontin(e)!garuniture à la ---e"
    "かるにちゆーる@ガルニチュール!ふさんそんふう@---・ブザンソン風"
    "ふさんそん@ブザンソン!かるにちゆーる@ガルニチュール・---風"
    "garniture@garniture!boulangere@--- à la Boulangère"
    "boulanger@boulanger/boulangère!garuniture à la ---ère"
    "かるにちゆーる@ガルニチュール!ふらんしえーる@---・ブランジェール"
    "ふらんしえ@ブランジェ/ブランジェール ⇒ パン屋!かるにちゆーる@ガルニチュール・ブランジェール"
    "はんや@パン屋 ⇒ ブランジェ/ブランジェール!かるにちゆーる@ガルニチュール・ブランジェール"
    "garniture@garniture!bouquetiere@--- à la Bouquetière"
    "bouquetiere@bouquetière!garuniture à la ---"
    "かるにちゆーる@ガルニチュール!ふくていえーる@---・ブクティエール"
    "ふくていえーる@ブクティエール ⇒ 花売り娘!かるにちゆーる@ガルニチュール・ブクティエール"
    "はなうりむすめ@花売り娘 ⇒ ブクティエール!かるにちゆーる@ガルニチュール・ブクティエール"
    "garniture@garniture!bourgeoise@--- à la Bourgeoise"
    "bourgeois@bourgeois(e)!garuniture à la ---"
    "かるにちゆーる@ガルニチュール!ふるしよわーす@---・ブルジョワーズ"
    "ふるしよわーす@ブルジョワーズ!かるにちゆーる@ガルニチュール・ブルジョワーズ"
    "ふるしよわふう@フルジョワ風 ⇒ ブルジョワーズ!かるにちゆーる@ガルニチュール・ブルジョワーズ"
    "garniture@garniture!brabanconne@--- à la Brabançonne"
    "brabanconne@brabançon(ne)!garuniture à la ---ne"
    "かるにちゆーる@ガルニチュール!ふらはんとふう@---・ブラバント風"
    "ふらはんとふう@ブラバント風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!brehan@--- Bréhan"
    "brehan@Bréhan!garuniture ---"
    "かるにちゆーる@ガルニチュール!ふれおん@---・ブレオン"
    "ふれおん@ブレオン!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!bretonne@--- à la Bretonne"
    "breton@breton(ne)!garuniture à la ---ne"
    "かるにちゆーる@ガルニチュール!ふるたーにゆふう@---・ブルターニュ風"
    "ふるたーにゆふう@ブルターニュ風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!brillat-savarin@--- Brillat-Savarin"
    "brillat-savarin@Brillat-Savarin!garuniture ---"
    "かるにちゆーる@ガルニチュール!ふりやさうあらん@---・ブリヤサヴァラン"
    "ふりやさうあらん@ブリヤサヴァラン!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!bristol@--- Bristol"
    "bristol@Bristol!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!ふりすとる@---・ブリストル"
    "ふりすとる@ブリストル!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!bruxelloise@--- à la Bruxelloise"
    "bruxellois@bruxellois(e)!garniture@garuniture à la ---e"
    "かるにちゆーる@ガルニチュール!ふりゆつせるふう@---・フリュッセル風"
    "ふりゆつせるふう@ブリュッセル風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!cancalaise@--- à la Cancalaise"
    "cancalais@cancalais(e)!garniture@garuniture à la ---e"
    "かるにちゆーる@ガルニチュール!かんかるふう@---・カンカル風"
    "かんかるふう@カンカル風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!cardinal@--- à la Cardinal"
    "cardinal@cardinal!garniture@garuniture à la ---"
    "かるにちゆーる@ガルニチュール!かるていなる@---・カルディナル"
    "かるていなる@カルディナル!かるにちゆーる@ガルニチュール・---"
    "すうききよう@枢機卿 ⇒ カルディナル!かるにちゆーる@ガルニチュール・カルディナル"
    "garniture@garniture!castillane@--- à la Castillane"
    "castillan@castillan(e)!garniture@garuniture à la ---e"
    "かるにちゆーる@ガルニチュール!かすていりあふう@---・カスティリア風"
    "かすていりあふう@カスティリア風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!chambord@--- Chambord"
    "chambord@Chambord!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!しやんほーる@---・シャンボール"
    "しやんほーる@シャンボール!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!chatelaine@--- Châtelaine"
    "chatelaine@Châtelaine!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!しやとれーぬ@---・シャトレーヌ"
    "しやとれーぬ@シャトレーヌ!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!chipolata@--- à la Chipolata"
    "chipolata@chipolata!garniture@garuniture à la ---"
    "かるにちゆーる@ガルニチュール!しほらた@---・シポラタ"
    "しほらた@シポラタ!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!choisy@--- Choisy"
    "choisy@Choisy!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!しよわしー@---・ショワジー"
    "しよわしー@ショワジー!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!choron@--- Choron"
    "choron@Choron!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!しよろん@---・ショロン"
    "しよろん@ショロン!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!clamart@--- à la Clamart"
    "clamart@Clamart!garniture@garuniture à la ---"
    "かるにちゆーる@ガルニチュール!くらまーる@---・クラマール"
    "くらまーる@クラマール!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!compote@--- de Compote"
    "compote@compote!garniture@garuniture de ---"
    "かるにちゆーる@ガルニチュール!こんほーと@---・コンポート"
    "こんほーと@コンポート!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!conti@--- Conti"
    "conti@Conti!garniture@garuniture de ---"
    "かるにちゆーる@ガルニチュール!こんてい@---・コンティ"
    "こんてい@コンティ!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!commodore@--- à la Commodore"
    "commodore@commodore!garniture@garuniture de ---"
    "かるにちゆーる@ガルニチュール!こもとーる@---・コモドール"
    "こもとーる@コモドール!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!cussy@--- Cussuy"
    "cussy@Cussy (marquis de)!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!きゆしー@---・キュシー"
    "きゆしー@キュシー!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!daumont@--- Daumont"
    "daumont@Daumont!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!ともん@---・ドモン"
    "ともん@ドモン!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!dauphine@--- à la Dauphine"
    "dauphin@dauphin(e)!garniture@garuniture ---e"
    "かるにちゆーる@ガルニチュール!とふいぬ@---・ドフィーヌ"
    "とふあん@ドファン/ドフィーヌ!かるにちゆーる@ガルニチュール・ドフィーヌ"
    "garniture@garniture!dieppoise@--- à la Dieppoise"
    "dieppois@dieppois(e)!garniture@garuniture ---e"
    "かるにちゆーる@ガルニチュール!ていえーふふう@---・ディエープ風"
    "ていえーふふう@ディエープ風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!doria@--- Doria"
    "doria@Doria!garniture@garuniture ---e"
    "かるにちゆーる@ガルニチュール!とりあ@---・ドリア"
    "とりあ@ドリア!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!dubarry@--- Dubarry"
    "dubarry@Dubarry!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!とゆはりー@---・デュバリー"
    "とゆはりー@デュバリー!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!duchesse@--- à la Duchesse"
    "duc@duc / duchesse!garniture@garuniture à la Duchesse"
    "かるにちゆーる@ガルニチュール!てゆせす@---・デュシェス"
    "てゆしえす@デュシェス!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!favorite@--- à la Favorite"
    "favorite@Favorige (La)!garniture@garuniture à la Favorite"
    "かるにちゆーる@ガルニチュール!らふあうおりーた@---・ラファヴォリータ"
    "らふあうおりーた@ラファヴォリータ!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!fermiere@--- à la Fermière"
    "fermier@fermier/fermière!garniture@garuniture à la Fermière"
    "かるにちゆーる@ガルニチュール!ふえるみえーる@---・フェルミエール"
    "ふえるみえ@フェルミエ/フェルミエール!かるにちゆーる@ガルニチュール・フェルミエール"
    "garniture@garniture!financiere@--- à la Financière"
    "financier@financier/financère!garniture@garuniture à la Financière"
    "かるにちゆーる@ガルニチュール!ふいなんしえーる@---・フィナンシエール"
    "ふいなんしえ@フィナンシエ/フィナンシエール!かるにちゆーる@ガルニチュール・フィナンシエール"
    "garniture@garniture!flamande@--- à la Flamande"
    "flamand@flamand(e)!garniture@garuniture à la ---e"
    "かるにちゆーる@ガルニチュール!ふらんとるふう@---・フランドル風"
    "ふらんとるふう@フランドル風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!florentine@--- à la Florentine"
    "florentin@florentin(e)!garniture@garuniture à la ---e"
    "かるにちゆーる@ガルニチュール!ふいれんつえふう@---・フィレンツェ風"
    "ふいれんつえふう@フィレンツェ風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!florian@--- Florian"
    "florian@Florian!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!ふろーりあん@---・フローリアン"
    "ふろーりあん@フローリアン!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!forestiere@--- à la Forestière"
    "forestier@forestier/forestière!garniture@garuniture à la Forestière"
    "かるにちゆーる@ガルニチュール!ふおれすていえーる@---・フォレスティエール"
    "ふおれすていえーる@フォレスティエール!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!forestiere@--- Frascati"
    "frascati@Frascati!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!ふらすかーてい@---・フラスカーティ"
    "ふらすかーてい@フラスカーティ!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!gastronome@--- à la Gastronome"
    "gastronome@gastronome!garniture@garuniture à la ---"
    "かるにちゆーる@ガルニチュール!かすとろのーむ@---・ガストロノーム"
    "かすとろのーむ@ガストロノーム!かるにちゆーる@ガルニチュール・---"
    "ひしよくかふう@美食家風 ⇒ ガストロノーム!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!godard@--- Godard"
    "godard@Godard!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!こたーる@---・ゴダール"
    "こたーる@ゴダール!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!grand-duc@--- Grand-Duc"
    "grand-duc@grand-duc!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!くらんていゆつく@---・グランデュック"
    "くらんていゆすく@グランデュック!かるにちゆーる@ガルニチュール・---"
    "たいこう@大公（風）⇒グランデュック!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!grecque@--- à la  Grecque"
    "grec@grec/grecque!garniture@garuniture à la grecque"
    "かるにちゆーる@ガルニチュール!くれつく@---・グレック"
    "くれいつく@グレック!かるにちゆーる@ガルニチュール・---"
    "きりしあふう@ギリシャ風⇒グレック!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!henri iV@--- Henri IV"
    "henri iv@Henri IV!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!あんりよんせいていふう@---・アンリ4世亭風"
    "あんりよんせいていふう@アンリ4世亭風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!hongroise@--- à la Hongroise"
    "hongrois@hongrois(e)!garniture@garuniture à la ---e"
    "かるにちゆーる@ガルニチュール!はんかりーふう@---・ハンガリー風"
    "はんかりーふう@ハンガリー風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!italienne@--- à l'Italienne"
    "italien@italien(ne)!garniture@garuniture à l' ---ne"
    "かるにちゆーる@ガルニチュール!いたりあふう@---・イタリア風"
    "いたりあふう@イタリア風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!indienne@--- à l'Indienne"
    "indien@indien(ne)!garniture@garuniture à l' ---ne"
    "かるにちゆーる@ガルニチュール!いんとふう@---・インド風"
    "いんとふう@インド風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!japonaise@--- à la Japonaise"
    "japonais@japonais(e)!garniture@garuniture à la ---e"
    "かるにちゆーる@ガルニチュール!にほんふう@---・日本風"
    "にほんふう@日本風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!jardiniere@--- à la Jardinière"
    "jardinier@jardinier/jardinière!garniture@garuniture à la Jardinière"
    "かるにちゆーる@ガルニチュール!しやるていにえーる@---・ジャルディニエール"
    "しやるていにえーる@ジャルディニエール!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!joinville@--- Joinville"
    "joinville@Joinille!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!しよわんういる@---・ジョワンヴィル"
    "しよわんういる@ジョワンヴィル!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!judic@--- Judic"
    "judic@Judic!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!しゆていつく@---・ジュディック"
    "しゆていつく@ジュディック!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!languedocienne@--- Languedocienne"
    "languedocien@languedocien(ne)!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!らんくとつくふう@---・ラングドック風"
    "らんくとつくふう@ラングドック風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!lorette@--- Lorette"
    "lorette@lorette!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!ろれつと@---・ロレット"
    "ろれつと@ロレット!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!louisiane@--- Louisiane"
    "louisiane@Louisiane!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!るいしあなふう@---・ルイジアナ風"
    "るいしあなふう@ルイジアナ風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!lucullus@--- Lucullus"
    "lucculus@Lucullus!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!るくつるす@---・ルクッルス"
    "るくつるす@ルクッルス!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!macedoine@--- Macédoine"
    "macedoine@macédoine!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!ませとわーぬ@---・マセドワーヌ"
    "ませとわーぬ@マセドワーヌ!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!madeleine@--- Madeleine"
    "madeleine@Madeleine!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!まとれーぬ@---・マドレーヌ"
    "まとれーぬ@マドレーヌ!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!maraichere@--- à la Maraîchère"
    "maraicher@maraîcher/maraîchère!garniture@garuniture à la Maraîchère"
    "かるにちゆーる@ガルニチュール!まれしえーる@---・マレシェール"
    "まれしえーる@マレシェール!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!marrechal@--- Maréchal"
    "marechal@maréchal!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!まれしやる@---・マレシャル"
    "まれしやる@マレシャル!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!marie-louise@--- Marie-Louise"
    "marie-louise@Marie-Louise (d'Autriche)!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!まりるいーす@---・マリ=ルイーズ"
    "まりるいーす@マリ=ルイーズ!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!mariniere@--- à la Marinière"
    "mariniere@marinière!garniture@garuniture à la ---"
    "かるにちゆーる@ガルニチュール!まりにえーる@---・マリニエール"
    "まりにえーる@マリニエール!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!marquise@--- Marquise"
    "marquise@marquise!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!まるきーす@---・マルキーズ"
    "まるきーす@マルキーズ!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!marseillaise@--- à la Marseillaise"
    "marseillais@marseillais(e)!garniture@garuniture ---e"
    "かるにちゆーる@ガルニチュール!まるせいえーす@---・マルセイエーズ"
    "まるせいえーす@マルセイエーズ!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!mascotte@--- Mascotte"
    "mascotte@Mascotte!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!ますこつと@---・マスコット"
    "ますこつと@マスコット!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!massena@--- Masséna"
    "massena@Masséna!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!ませな@---・マセナ"
    "ませな@マセナ!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!matelote@--- Matelote"
    "matelote@matelote!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!まとろつと@---・マトロット"
    "まとろつと@マトロット!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!medicis@--- Médicis"
    "medicis@médicis!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!めていしす@---・メディシス"
    "めていしす@メディシス!かるにちゆーる@ガルニチュール・---"
    "めていちけ@メディチ家 ⇒ メディシス!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!mexicaine@--- à la Mexicaine"
    "mexicain@mexicain(e)!garniture@garuniture à la ---"
    "かるにちゆーる@ガルニチュール!めきしこふう@---・メキシコ風"
    "めきしこふう@メキシコ風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!mignon@--- Mignon"
    "mignon@mignon!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!みによん@---・ミニョン"
    "みによん@ミニョン!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!milanaise@--- à la Milanaise"
    "milanais@milanais(e)!garniture@garuniture ---e"
    "かるにちゆーる@ガルニチュール!みらのふう@---・ミラノ風"
    "みらのふう@ミラノ風!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!mirabeau@--- Mirabeau"
    "mirabeau@Mirabeau!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!みらほー@---・ミラボー"
    "みらほー@ミラボー!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!mirette@--- Mirette"
    "mirette@mirette!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!みれつと@---・ミレット"
    "みれつと@ミレット!かるにちゆーる@ガルニチュール・---"
    "garniture@garniture!moderne@--- à la Moderne"
    "moderne@moderne!garniture@garuniture à la ---"
    "かるにちゆーる@ガルニチュール!あらもてるぬ@---・アラモデルヌ"
    "もてるぬ@モデルヌ（アラ）!かるにちゆーる@ガルニチュール・アラモデルヌ"
    "きんたいふう@近代風 ⇒ アラモデルヌ!かるにちゆーる@ガルニチュール・アラモデルヌ"
    "garniture@garniture!montbazon@--- Montbazon"
    "montbazon@montbazon!garniture@garuniture ---"
    "かるにちゆーる@ガルニチュール!もんはそん@---・モンバゾン"
    "もんはそん@モンバゾン!かるにちゆーる@ガルニチュール・---"))
 :latex)

