(TeX-add-style-hook
 "02-02-pp78-82"
 (lambda ()
   (LaTeX-add-labels
    "serie-des-appareiles-et-preparations-diverses-pour-garnitures-chaudes"
    "appareils-a-cromesquis-et-a-croquettes"
    "appareils-a-pomme-dauphine-duchesse-marquise"
    "appareil-maintenon"
    "appareil-montglas"
    "appareil-provencal"
    "bordures-en-farce"
    "bordures-en-legumes"
    "bordures-en-pate-blanche"
    "bordures-en-pate-a-nouille"
    "croutons"
    "duxelles-seche"
    "duxelles-pour-legumes-farcis"
    "duxelles-pour-farnitures-diverses"
    "duxelles-bonne-femme"
    "essence-de-tomate"
    "nota-essence-de-tomate"
    "fonds-de-plats"
    "ux7c73ux3067ux4f5cux308bux30c8ux30f3ux30ddux30f3ux3068ux30afux30ebux30b9ux30bfux30fcux30c9"
    "portugaise"
    "kache-de-sarrazin-pour-potage"
    "nota-kache-de-sarrazin-pour-potage"
    "kache-de-semoule-pour-coulibiac"
    "matignon"
    "mirepoix"
    "mirepoix-fine"
    "nota-mirepoix-fine"
    "orge-perle-pour-volailles-farcies"
    "pate-a-chou-d-office"
    "pate-a-frire-pour-beignet-de-cervelles"
    "pate-a-frire-pour-legumes"
    "riz-pour-farcir-les-volailles-servies-en-releve-ou-en-entree"
    "nota-riz-pour-farcir-les-volailles-servies-en-releve-ou-en-entree"
    "salpicons-divers"
    "ux30d4ux30edux30b7ux30adux7528ux30c8ux30f4ux30a1ux30edux30fcux30b072")
   (LaTeX-add-index-entries
    "garniture@garniture!appareils chaudes@appareils et préparations diverses pour ---s chaudes"
    "appareil@appareil!garnitures chaudes@--- et préparations diverses pour garnitures chaudes"
    "かるにちゆーる@ガルニチュール!あはれいゆおんせい@温製---のためのアパレイユなど"
    "あはれいゆ@アパレイユ!おんせいかるにちゆーる@温製ガルニチュールのための---など"
    "appareil@appareil!cromesquis croquettes@---s à cromesquis et à croquettes"
    "cromesqui@cromesqui!appareil@appareils à --- et à croquettes"
    "croquette@croquette!appareil@appareils à cromesquis et à ---"
    "あはれいゆ@アパレイユ!くろめすきとくろけつと@クロケットとクロメスキの---"
    "くろめすき@クロメスキ!あはれいゆ@---とクロケットのアパレイユ"
    "くろけつと@クロケット!あはれいゆ@クロメスキと---のアパレイユ"
    "appareil@appareil!pomme dauphine@---s à pomme Dauphine, Duchesse et Marquise"
    "dauphin@dauphin(e)!appareil@appareil à pomme ---e"
    "duc@duc / duchesse!appareil@appareil à pomme duchesse"
    "marquis@marquis(s)!appareil@appareil à pomme ---e"
    "あはれいゆ@アパレイユ!しやかいものとふいーぬと@じゃがいものドフィーヌ、デュシェス、マルキーズの---"
    "とふいーぬ@ドフィーヌ!あはれいゆ@アパレイユ!しやかいものとふいーぬ@じゃがいもの---、デュシェス、マルキーズのアパレイユ"
    "てゆしえす@デュシェス!あはれいゆ@アパレイユ!しやかいものてゆしえす@じゃがいものドフィーヌ、---、マルキーズのアパレイユ"
    "まるきーす@マルキーズ!あはれいゆ@アパレイユ!しやかいものまるきーす@じゃがいものドフィーヌ、デュシェス、---のアパレイユ"
    "appareil@appareil!maintenon@--- Maintenon"
    "maintenon@Maintenon!appareil@appareil ---"
    "あはれいゆ@アパレイユ!まんとのん@---・マントノン"
    "まんとのん@マントノン!あはれいゆ@アパレイユ・---"
    "appareil@appareil!montglas@--- à l Montglas"
    "montglas@Montglas!appareil@appareil à la ---"
    "あはれいゆ@アパレイユ!もんくら@---・モングラ"
    "もんくら@モングラ!あはれいゆ@アパレイユ・---"
    "appareil@appareil!provencale@--- à la Provençale"
    "provençal@provençale(e)!appareil@appareil à la ---e"
    "あはれいゆ@アパレイユ!ふろうあんすふう@プロヴァンス風---"
    "ふろうあんすふう@プロヴァンス風!あはれいゆ@---アパレイユ"
    "bordure@bordure!farce@--- en farce"
    "farce@farce!bordures@bordures en ---"
    "ふあるす@ファルス!ふちかざり@---で作る縁飾り"
    "ほるてゆーる@ボルデュール ⇒ 縁飾り!ふぁるす@ファルスで作る縁飾り"
    "ふちかさり@縁飾り!ふあるす@ファルスで作る---"
    "bordure@bordure!legumes@--- en légumes"
    "legume@légume!bordures@bordures en ---s"
    "やさい@野菜!ふちかざり@---で作る縁飾り"
    "ほるてゆーる@ボルデュール ⇒ 縁飾り!やさい@野菜で作る縁飾り"
    "ふちかさり@縁飾り!やさい@野菜で作る---"
    "bordure@bordure!pate blanche@--- en pâte blanche"
    "pate blanche@pâte blanche!bordures@bordures en ---s"
    "きし@生地!しろいふちかざり@白い生地で作る縁飾り"
    "ほるてゆーる@ボルデュール ⇒ 縁飾り!しろいきし@白い生地で作る縁飾り"
    "ふちかさり@縁飾り!しろいきし@白い生地で作る野菜---"
    "はーと@パート ⇒ 生地!しろいふちかざり@白い生地で作る縁飾り"
    "bordure@bordure!pate nouille@--- en pâte à nouille"
    "nouille@nouille!bordures@bordures en pâte à ---"
    "きし@生地!ぬいゆふちかざり@ヌイユ生地で作る縁飾り"
    "ほるてゆーる@ボルデュール ⇒ 縁飾り!ぬいゆきし@ヌイユ生地で作る縁飾り"
    "ふちかさり@縁飾り!ぬいゆきし@ヌイユ生地で作る野菜---"
    "はーと@パート ⇒ 生地!ぬいゆふちかざり@ヌイユ生地で作る縁飾り"
    "croutons@croûtons"
    "くるとん@クルトン"
    "champignon@champignon!duxelles seche@duxelles sèche"
    "duxelles@duxelles!seche@--- sèche"
    "てゆくせる@デュクセル!せつしゆ@---・セッシュ"
    "まつしゆるーむ@マッシュルーム!てゆくせる@デュクセル!せつしゆ@デュクセル・セッシュ"
    "champignon@champignon!duxelles legumes farcis@duxelles pour légumes farcis"
    "duxelles@duxelles!legumes farcis@--- pour légumes farcis"
    "てゆくせる@デュクセル!やさいのふあるしよう@野菜のファルシ用---"
    "まつしゆるーむ@マッシュルーム!てゆくせる@デュクセル!やさいのふあるしよう@野菜のファルシ用デュクセル"
    "champignon@champignon!duxelles pour garnitures diverses@duxelles pour garnitures diverses"
    "duxelles@duxelles!garnitures diverses@--- pour garnitures diverses"
    "てゆくせる@デュクセル!かるにちゆーるよう@ガルニチュール用---"
    "まつしゆるーむ@マッシュルーム!てゆくせる@デュクセル!かるにちゆーるよう@ガルニチュール用デュクセル"
    "champignon@champignon!duxelles bonne femme@duxelles à la bonne femme"
    "duxelles@duxelles!bonne femme@--- à la bonne femme"
    "bonne femme@bonne femme!duxelles@duxelles à la ---"
    "てゆくせる@デュクセル!ほぬふあむ@---・ボヌファム"
    "ほぬふあむ@ボヌファム!てゆくせる@デュクセル・---"
    "まつしゆるーむ@マッシュルーム!てゆくせる@デュクセル!ほぬふあむ@デュクセル・ボヌファム"
    "tomate@tomate!essence@essence de ---"
    "essence@essence!tomate@--- de tomate"
    "とまと@トマト!えつせんす@---エッセンス"
    "えつせんす@エッセンス!トマト---"
    "fonds@fonds!plats@--- de plats"
    "tampon@tampon"
    "croustade@croustade"
    "たい@台!さらにしいてりようりをのせる@皿に敷いて料理をのせる---"
    "とんぽん@トンポン"
    "くるすたーと@クルスタード"
    "tomate@tomate!fondue@fondue de --- ou Portugaise"
    "portugais@portugais(e)!fondue de tomate@foudue de tomate ou Portugaise"
    "とまと@トマト!ふおんてゆ@---のフォンデュ/ポルチュゲーズ"
    "ふおんてゆ@フォンデュ!とまと@トマトの---/ポルチュゲーズ"
    "ほるちゆけーす@ポルチュゲーズ/トマトのフォンデュ"
    "ほるとかるふう@ポルトガル風!ほるちゆけーす@ポルチュゲーズ/トマトのフォンデュ"
    "kache@kache!sarrazin@--- de Sarrazin pour Potages"
    "sarrazin@sarrazin!kache@Kache de --- pour Potages"
    "かーしや@カーシャ!そはこ@ポタージュ用そば粉の---"
    "そはこ@そば粉!かーしや@ポタージュ用---のカーシャ"
    "kache@kache!semoule@--- de Semoule pour le Coulibiac"
    "semoule@semoule!kache@Kache de --- pour le Coulibiac"
    "かーしや@カーシャ!せもりなこ@クリビヤック用セモリナ粉の---"
    "せもりなこ@セモリナ粉!かーしや@クリビヤック用セモリナ粉---のカーシャ"
    "くりひやつく@クリビヤック!かーしや@---そば粉のカーシャ"
    "matignon@matignon"
    "まていによん@マティニョン"
    "mirepoix@mirepoix"
    "みるほわ@ミルポワ"
    "mirepoix@mirepoix!fine@ --- fine, dite à la Bordelaise"
    "bordelais@bordelais(e)!mirepoix fine@mirepoix fine, dite à la ---e"
    "みるほわ@ミルポワ!ほるとーふう@ボルドー風ミルポワ"
    "ほるとーふう@ボルドー風!みるほわ@---ミルポワ"
    "orge perle@orge perlé"
    "しんしゆむき@真珠麦!まるとりのつめもの@丸鶏の詰め物その他に用いる真珠麦"
    "おおむぎ@大麦!せいはく@精白--- ⇒ 丸鶏の詰め物その他に用いる真珠麦"
    "まるむぎ@丸麦 ⇒ 真珠麦!まるとりのつめもの@丸鶏の詰め物その他に用いる真珠麦"
    "pate@pâte!chou@chou!office@pâte à chou d'office"
    "choupate@chou (pâte)!office@pâte à --- d'office"
    "しゆうきし@シュー生地!ちようりよう@調理用---"
    "きし@生地!ちようりようしゆー@調理用シュー生地"
    "pate@pâte!frire@--- à frire!beignet cervelles@pâte à frire pour Beignets de cervelles et de laitances, fritots, etc."
    "frire@frire!pate@pâte à ---!beignet cervelles@pâte à frire pour Beignet de cervelles et de laitances, fritots; etc."
    "fritot@fritot!pate frire@pâte à frire pour Beignet de cervelles et de laitances, fritots; etc."
    "cervelle@cervelle!pate frire@pâte à frire pour Beignet de cervelles et de laitances, fritots; etc."
    "laitance@laitance!pate frire@pâte à frire pour Beignet de cervelles et de laitances, fritots; etc."
    "あけころも@揚げ衣!のうしらこのへにえやふりとー@脳、白子のベニェやフリトー用の揚げ衣"
    "ふりとー@フリトー!のうしらこのへにえやふりとようあけころも@脳、白子のベニェやフリトー用の揚げ衣"
    "のう@脳!のうしらこのへにえやふりとーようあけころも@脳、白子のベニェやフリトー用の揚げ衣"
    "しらこ@白子!のうしらこのへにえやふりとーようあけころも@脳、白子のベニェやフリトー用の揚げ衣"
    "pate@pâte!frire@--- à frire!legumes@pâte à frire pour Légumes"
    "frire@frire!pate legumes@pâte à frire pour Légumes"
    "legumes@legumes!pate frire@pâte à frire pour Légumes"
    "salsifis@salsifis!pate frire@pâte à frire pour Légumes"
    "celeris@céleris!pate frire@pâte à frire pour Légumes"
    "crosnes@crosnes!pate frire@pâte à frire pour Légumes"
    "あけころも@揚げ衣!やさいよう@野菜用の揚げ衣"
    "さすしふい@サルシフィ!やさいようのあけころも@野菜用の揚げ衣"
    "せろり@セロリ!やさいようのあけころも@野菜用の揚げ衣"
    "ちよろき@チョロギ!やさいようのあけころも@野菜用の揚げ衣"
    "riz@riz!farcir@--- pour farcir les volailles servies en Relevé ou en Entrée"
    "farce@farce!riz@riz pour farcir les volailles servies en Relevé ou en Entrée"
    "ふあるす@ファルス!おおさらしたてのまるとりにつめるこめ@大皿仕立ての丸鶏に詰める米"
    "こめ@米!つめもの@大皿仕立ての丸鶏に詰める米"
    "salpicon@salpicon"
    "さるひこん@サルピコン"
    "piroguis@piroguie!twarogue@twarogue pour ---"
    "twarogue@twaroguel!piroguis@--- pour piroguis"
    "cuisine russe@cuisine russe!twarogue@twarogue pour piroguis"
    "とうあろーく@トヴァローグ"
    "ろしあふう@ロシア風!ひろしきようとうあろーく@ピロシキ用トヴァローグ"
    "ひろしき@ピロシキ!とうあろーく@---用トゥヴァローグ"))
 :latex)

